"use strict";
// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file plugins/openai/v1/plugin.proto (package plugins.openai.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.Plugin = exports.Custom = exports.Property = exports.SuperblocksMetadata = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from message plugins.openai.v1.SuperblocksMetadata
 */
class SuperblocksMetadata extends protobuf_1.Message {
    /**
     * @generated from field: string pluginVersion = 1;
     */
    pluginVersion = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "plugins.openai.v1.SuperblocksMetadata";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "pluginVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new SuperblocksMetadata().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new SuperblocksMetadata().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new SuperblocksMetadata().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(SuperblocksMetadata, a, b);
    }
}
exports.SuperblocksMetadata = SuperblocksMetadata;
/**
 * @generated from message plugins.openai.v1.Property
 */
class Property extends protobuf_1.Message {
    /**
     * @generated from field: string key = 1;
     */
    key = "";
    /**
     * @generated from field: int32 value = 2;
     */
    value = 0;
    /**
     * @generated from field: bool editable = 3;
     */
    editable = false;
    /**
     * @generated from field: bool internal = 4;
     */
    internal = false;
    /**
     * @generated from field: string description = 5;
     */
    description = "";
    /**
     * @generated from field: bool mandatory = 6;
     */
    mandatory = false;
    /**
     * @generated from field: string type = 7;
     */
    type = "";
    /**
     * @generated from field: string defaultValue = 8;
     */
    defaultValue = "";
    /**
     * @generated from field: string minRange = 9;
     */
    minRange = "";
    /**
     * @generated from field: string maxRange = 10;
     */
    maxRange = "";
    /**
     * @generated from field: repeated string valueOptions = 11;
     */
    valueOptions = [];
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "plugins.openai.v1.Property";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "value", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
        { no: 3, name: "editable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
        { no: 4, name: "internal", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
        { no: 5, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 6, name: "mandatory", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
        { no: 7, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 8, name: "defaultValue", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 9, name: "minRange", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 10, name: "maxRange", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 11, name: "valueOptions", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    ]);
    static fromBinary(bytes, options) {
        return new Property().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Property().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Property().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Property, a, b);
    }
}
exports.Property = Property;
/**
 * @generated from message plugins.openai.v1.Custom
 */
class Custom extends protobuf_1.Message {
    /**
     * @generated from field: plugins.openai.v1.Property presignedExpiration = 1;
     */
    presignedExpiration;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "plugins.openai.v1.Custom";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "presignedExpiration", kind: "message", T: Property },
    ]);
    static fromBinary(bytes, options) {
        return new Custom().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Custom().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Custom().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Custom, a, b);
    }
}
exports.Custom = Custom;
/**
 * @generated from message plugins.openai.v1.Plugin
 */
class Plugin extends protobuf_1.Message {
    /**
     * @generated from field: string action = 1;
     */
    action = "";
    /**
     * @generated from field: optional string generateChatGptResponsePrompt = 2;
     */
    generateChatGptResponsePrompt;
    /**
     * @generated from field: optional string generateChatGptResponseMessageHistory = 3;
     */
    generateChatGptResponseMessageHistory;
    /**
     * @generated from field: optional string generateChatGptResponseSystemInstruction = 4;
     */
    generateChatGptResponseSystemInstruction;
    /**
     * @generated from field: optional string generateTextType = 5;
     */
    generateTextType;
    /**
     * @generated from field: optional string generateTextNewTextPrompt = 6;
     */
    generateTextNewTextPrompt;
    /**
     * @generated from field: optional string generateTextEditTextTextToEdit = 7;
     */
    generateTextEditTextTextToEdit;
    /**
     * @generated from field: optional string generateTextEditTextPrompt = 8;
     */
    generateTextEditTextPrompt;
    /**
     * @generated from field: optional string generateCodeType = 9;
     */
    generateCodeType;
    /**
     * @generated from field: optional string generateCodeNewCodePrompt = 10;
     */
    generateCodeNewCodePrompt;
    /**
     * @generated from field: optional string generateCodeEditCodeCodeToEdit = 11;
     */
    generateCodeEditCodeCodeToEdit;
    /**
     * @generated from field: optional string generateCodeEditCodePrompt = 12;
     */
    generateCodeEditCodePrompt;
    /**
     * @generated from field: optional string checkModerationText = 13;
     */
    checkModerationText;
    /**
     * @generated from field: optional string embeddingText = 14;
     */
    embeddingText;
    /**
     * @generated from field: optional string generateImageMethod = 15;
     */
    generateImageMethod;
    /**
     * @generated from field: optional string generateImageGenerateFromPromptPrompt = 16;
     */
    generateImageGenerateFromPromptPrompt;
    /**
     * @generated from field: optional string generateImageGenerateFromPromptImageImageSize = 17;
     */
    generateImageGenerateFromPromptImageImageSize;
    /**
     * @generated from field: optional string generateImageEditImagePrompt = 18;
     */
    generateImageEditImagePrompt;
    /**
     * @generated from field: optional string generateImageEditImageImageFileToEdit = 19;
     */
    generateImageEditImageImageFileToEdit;
    /**
     * @generated from field: optional string generateImageEditImageImageMask = 20;
     */
    generateImageEditImageImageMask;
    /**
     * @generated from field: optional string generateImageEditImageImageSizes = 21;
     */
    generateImageEditImageImageSizes;
    /**
     * @generated from field: optional string generateImageVaryImageImageFile = 22;
     */
    generateImageVaryImageImageFile;
    /**
     * @generated from field: optional string generateImageVaryImageImageSize = 23;
     */
    generateImageVaryImageImageSize;
    /**
     * @generated from field: optional string transcribeAudioToTextAudioFile = 24;
     */
    transcribeAudioToTextAudioFile;
    /**
     * @generated from field: optional string transcribeAudioToTextInputLanguage = 25;
     */
    transcribeAudioToTextInputLanguage;
    /**
     * This is not a string because it is not a binding! Yay!
     *
     * @generated from field: bool transcribeAudioToTextTranslateToEnglish = 26;
     */
    transcribeAudioToTextTranslateToEnglish = false;
    /**
     * @generated from field: optional string generateChatGPTResponseAiModel = 27;
     */
    generateChatGPTResponseAiModel;
    /**
     * @generated from field: optional string generateTextNewTextAiModel = 28;
     */
    generateTextNewTextAiModel;
    /**
     * @generated from field: optional string generateTextEditTextAiModel = 29;
     */
    generateTextEditTextAiModel;
    /**
     * @generated from field: optional string generateCodeNewCodeAiModel = 30;
     */
    generateCodeNewCodeAiModel;
    /**
     * @generated from field: optional string generateCodeEditCodeAiModel = 31;
     */
    generateCodeEditCodeAiModel;
    /**
     * @generated from field: optional string checkModerationAiModel = 32;
     */
    checkModerationAiModel;
    /**
     * @generated from field: optional string generateTextEmbeddingAiModel = 33;
     */
    generateTextEmbeddingAiModel;
    /**
     * @generated from field: optional string transcribeAudioToTextAiModel = 34;
     */
    transcribeAudioToTextAiModel;
    /**
     * Super confusing - these fields might be bindings
     * Otherwise, they should be ints
     *
     * @generated from field: optional string generateChatGptResponseMaxTokens = 35;
     */
    generateChatGptResponseMaxTokens;
    /**
     * @generated from field: optional string generateTextNewTextMaxTokens = 36;
     */
    generateTextNewTextMaxTokens;
    /**
     * @generated from field: optional string aiModel = 37;
     */
    aiModel;
    /**
     * @generated from field: plugins.openai.v1.SuperblocksMetadata superblocksMetadata = 38;
     */
    superblocksMetadata;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "plugins.openai.v1.Plugin";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "action", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "generateChatGptResponsePrompt", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 3, name: "generateChatGptResponseMessageHistory", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 4, name: "generateChatGptResponseSystemInstruction", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 5, name: "generateTextType", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 6, name: "generateTextNewTextPrompt", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 7, name: "generateTextEditTextTextToEdit", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 8, name: "generateTextEditTextPrompt", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 9, name: "generateCodeType", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 10, name: "generateCodeNewCodePrompt", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 11, name: "generateCodeEditCodeCodeToEdit", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 12, name: "generateCodeEditCodePrompt", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 13, name: "checkModerationText", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 14, name: "embeddingText", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 15, name: "generateImageMethod", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 16, name: "generateImageGenerateFromPromptPrompt", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 17, name: "generateImageGenerateFromPromptImageImageSize", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 18, name: "generateImageEditImagePrompt", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 19, name: "generateImageEditImageImageFileToEdit", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 20, name: "generateImageEditImageImageMask", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 21, name: "generateImageEditImageImageSizes", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 22, name: "generateImageVaryImageImageFile", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 23, name: "generateImageVaryImageImageSize", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 24, name: "transcribeAudioToTextAudioFile", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 25, name: "transcribeAudioToTextInputLanguage", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 26, name: "transcribeAudioToTextTranslateToEnglish", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
        { no: 27, name: "generateChatGPTResponseAiModel", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 28, name: "generateTextNewTextAiModel", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 29, name: "generateTextEditTextAiModel", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 30, name: "generateCodeNewCodeAiModel", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 31, name: "generateCodeEditCodeAiModel", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 32, name: "checkModerationAiModel", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 33, name: "generateTextEmbeddingAiModel", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 34, name: "transcribeAudioToTextAiModel", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 35, name: "generateChatGptResponseMaxTokens", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 36, name: "generateTextNewTextMaxTokens", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 37, name: "aiModel", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 38, name: "superblocksMetadata", kind: "message", T: SuperblocksMetadata },
    ]);
    static fromBinary(bytes, options) {
        return new Plugin().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Plugin().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Plugin().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Plugin, a, b);
    }
}
exports.Plugin = Plugin;
//# sourceMappingURL=plugin_pb.map