{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "superblocks-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    external-secrets.io/force-sync: {{ now | date "2006-01-02T15:04:05Z" | quote }}
  labels:
    {{- include "superblocks-agent.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ include "superblocks-agent.fullname" . }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.agentKey.data | nindent 4 }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "superblocks-agent.redis-password-name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    external-secrets.io/force-sync: {{ now | date "2006-01-02T15:04:05Z" | quote }}
  labels:
    {{- include "superblocks-agent.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ include "superblocks-agent.redis-password-name" . }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.redisPassword.data | nindent 4 }}
{{- if .Values.externalSecrets.secretsEncryptionKey.data }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "superblocks-agent.secrets-encryption-key-name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    external-secrets.io/force-sync: {{ now | date "2006-01-02T15:04:05Z" | quote }}
  labels:
    {{- include "superblocks-agent.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ include "superblocks-agent.secrets-encryption-key-name" . }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.secretsEncryptionKey.data | nindent 4 }}
{{- end }}
{{- end }}
