---
codecov:
  require_ci_to_pass: true
  notify:
    manual_trigger: true
coverage:
  status:
    project:
      default:
        threshold: 0.5%
        if_ci_failed: error
    patch:
      default:
        if_ci_failed: error
ignore:
  - "./config/"
  - "./docs/"
  - "./mocks/"
  - "./types/"
  - "**/*_mock.go"
  - "**/mocks/*.go"
  - "**/*.test.ts"
  - "**/*_test.ts"
  - "**/gen/**"
  - "**/javascript-sandbox/src/types/"
  - "**/quickjs-emscripten/**"
