---
codecov:
  require_ci_to_pass: true
coverage:
  status:
    project:
      default:
        threshold: 0.5%
        if_ci_failed: error
    patch:
      default:
        if_ci_failed: error
flags:
  test-go:
    carryforward: true
  test-task-manager:
    carryforward: true
  test-js-unit:
    carryforward: true
  test-js-plugins-sandbox-unit:
    carryforward: true
  test-py-unit:
    carryforward: true
  test-py-sandbox:
    carryforward: true
  e2e-quotas:
    carryforward: true
  e2e-cloud:
    carryforward: true
  e2e-opa:
    carryforward: true
  superblocks-agent-client-python:
    carryforward: true
ignore:
  - "./config/"
  - "./docs/"
  - "./mocks/"
  - "./types/"
  - "**/*_mock.go"
  - "**/mocks/*.go"
  - "**/*.test.ts"
  - "**/*_test.ts"
  - "**/gen/**"
  - "**/javascript-sandbox/src/types/"
  - "**/quickjs-emscripten/**"
