---
# Docker Compose for ephemeral workers (task-manager + sandboxes)
# Used for e2e testing ephemeral Python and JavaScript execution
x-environment: &environment
  SUPERBLOCKS_AGENT_KEY: dev-agent-key
  SUPERBLOCKS_AGENT_REDIS_TOKEN: koala
  SUPERBLOCKS_AGENT_REDIS_KVSTORE_TOKEN: koala
  SUPERBLOCKS_AGENT_TLS_INSECURE: 'true'
  SUPERBLOCKS_AGENT_REDIS_HOST: redis
  SUPERBLOCKS_AGENT_REDIS_KVSTORE_HOST: redis
x-task-manager-environment: &task-manager-environment
  !!merge <<: *environment
  # Task-manager uses SUPERBLOCKS_WORKER_SANDBOX prefix for viper
  SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_REDIS_HOST: redis
  SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_REDIS_PORT: "6379"
  SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_REDIS_PASSWORD: koala
  SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_REDIS_TLS: "false"
  SUPERBLOCKS_WORKER_SANDBOX_STORE_REDIS_HOST: redis
  SUPERBLOCKS_WORKER_SANDBOX_STORE_REDIS_PORT: "6379"
  SUPERBLOCKS_WORKER_SANDBOX_STORE_REDIS_PASSWORD: koala
  SUPERBLOCKS_WORKER_SANDBOX_STORE_REDIS_TLS: "false"
  # Don't exit after one job (ephemeral=false) - allows task-manager to process multiple jobs
  SUPERBLOCKS_WORKER_SANDBOX_WORKER_EPHEMERAL: "false"
x-task-manager-base: &task-manager-base
  image: ghcr.io/superblocksteam/task-manager:${EPHEMERAL_IMAGE_TAG:-latest}
  build:
    context: .
    dockerfile: Dockerfile.worker.task-manager
  depends_on:
    - redis
  environment:
    !!merge <<: *task-manager-environment
  networks:
    - default
x-python-lang-executor-sandbox-base: &python-lang-executor-sandbox-base
  image: ghcr.io/superblocksteam/python-lang-executor-sandbox:${EPHEMERAL_IMAGE_TAG:-latest}
  build:
    context: .
    dockerfile: Dockerfile.sandbox-lang-executor.python
  networks:
    - default
x-javascript-lang-executor-sandbox-base: &javascript-lang-executor-sandbox-base
  image: ghcr.io/superblocksteam/javascript-lang-executor-sandbox:${EPHEMERAL_IMAGE_TAG:-latest}
  build:
    context: .
    dockerfile: Dockerfile.sandbox-lang-executor.javascript
  networks:
    - default
services:
  # Redis is shared with compose.full.yaml
  redis:
    image: docker.io/valkey/valkey:8.1.5-alpine
    ports:
      - 6379:6379
    command: --requirepass koala
    pull_policy: always
  # ============================================================================
  # Python Ephemeral Workers
  # ============================================================================
  python-lang-executor-sandbox:
    !!merge <<: *python-lang-executor-sandbox-base
    container_name: python-lang-executor-sandbox
  python-ephemeral:
    !!merge <<: *task-manager-base
    container_name: python-ephemeral
    environment:
      !!merge <<: *task-manager-environment
      SUPERBLOCKS_WORKER_SANDBOX_WORKER_PLUGINS: python
      SUPERBLOCKS_WORKER_SANDBOX_WORKER_EVENTS: execute
      SUPERBLOCKS_WORKER_SANDBOX_WORKER_BUCKETS: BA BE B1 B2
      SUPERBLOCKS_WORKER_SANDBOX_SANDBOX_ADDRESS: python-lang-executor-sandbox:50051
      SUPERBLOCKS_WORKER_SANDBOX_VARIABLE_STORE_GRPC_ADDRESS: python-ephemeral:50050
      SUPERBLOCKS_WORKER_SANDBOX_VARIABLE_STORE_HTTP_PORT: 8080
      SUPERBLOCKS_WORKER_SANDBOX_STREAMING_PROXY_GRPC_PORT: 50052
      SUPERBLOCKS_WORKER_SANDBOX_WORKER_SANDBOX_STREAMS_SEPARATE: true
    depends_on:
      - redis
      - python-lang-executor-sandbox
  # ============================================================================
  # JavaScript Ephemeral Workers
  # ============================================================================
  javascript-lang-executor-sandbox:
    !!merge <<: *javascript-lang-executor-sandbox-base
    container_name: javascript-lang-executor-sandbox
    environment:
      SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_VARIABLE_STORE_HTTP_ADDRESS: javascript-ephemeral:8080
  javascript-ephemeral:
    !!merge <<: *task-manager-base
    container_name: javascript-ephemeral
    environment:
      !!merge <<: *task-manager-environment
      SUPERBLOCKS_WORKER_SANDBOX_WORKER_PLUGINS: javascript
      SUPERBLOCKS_WORKER_SANDBOX_WORKER_EVENTS: execute
      SUPERBLOCKS_WORKER_SANDBOX_WORKER_BUCKETS: BA BE B1 B2
      SUPERBLOCKS_WORKER_SANDBOX_SANDBOX_ADDRESS: javascript-lang-executor-sandbox:50051
      SUPERBLOCKS_WORKER_SANDBOX_VARIABLE_STORE_GRPC_ADDRESS: javascript-ephemeral:50050
      SUPERBLOCKS_WORKER_SANDBOX_VARIABLE_STORE_HTTP_PORT: 8080
      SUPERBLOCKS_WORKER_SANDBOX_STREAMING_PROXY_GRPC_PORT: 50052
      SUPERBLOCKS_WORKER_SANDBOX_WORKER_SANDBOX_STREAMS_SEPARATE: true
    depends_on:
      - redis
      - javascript-lang-executor-sandbox
networks:
  default:
    name: orchestrator_default
    external: true
