---
services:
  jaeger:
    image: jaegertracing/all-in-one:1.53
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "5778:5778"
      - "16686:16686" # This one is the UI.
      - "14268:14268"
      - "14250:14250"
      - "4317:4317"
      - "4318:4318"
