# syntax=docker/dockerfile:1.9.0

FROM ghcr.io/superblocksteam/golang:1.25.5-trixie AS builder

ARG GO_ARCH=amd64
ARG SERVICE_VERSION=v0.0.0

WORKDIR /go/src/github.com/superblocksteam/agent

ENV DEBIAN_FRONTEND=noninteractive

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download

COPY . .

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
    dpkg --add-architecture amd64 \
    && apt-get update \
    && apt-get install -y --no-install-recommends build-essential gcc

# Build our binary.
# TODO: build arm binary
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    GOOS=linux GOARCH=${GO_ARCH} make build-go SERVICE_NAME="worker.go"                     \
                                               SERVICE_VERSION=${SERVICE_VERSION}             \
                                               GO_BUILD_ROOT_DIRECTORY="./workers/golang"   \
                                               EXTRA_LD_FLAGS="-s -w -extldflags '-dynamic'"

# Build the final image
FROM ghcr.io/superblocksteam/debian:trixie-20250811-slim

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
    apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends ca-certificates

# Copy in our compiled binary
COPY --from=builder /go/src/github.com/superblocksteam/agent/workers/golang/worker.go /worker-go

# Start the service
ENTRYPOINT ["/worker-go"]
