{{- if .Values.worker.podDisruptionBudget -}}
{{- range $k, $v := $.Values.worker.fleets }}
---
{{- if semverCompare ">=1.21-0" $.Capabilities.KubeVersion.GitVersion }}
apiVersion: policy/v1
{{ else }}
apiVersion: policy/v1beta1
{{- end -}}
kind: PodDisruptionBudget
metadata:
  name: {{ include "superblocks-agent.worker.fleet.name" (dict "Global" $ "fleet" $k) }}
  labels:
    {{- include "superblocks-agent.labels" $ | nindent 4 }}
    {{- include "superblocks-agent.worker.labels" $k | nindent 4 }}
spec:
{{- $.Values.worker.podDisruptionBudget | toYaml | nindent 2 }}
  selector:
    matchLabels:
      {{- include "superblocks-agent.selectorLabels" $ | nindent 6 }}
      {{- include "superblocks-agent.worker.labels" $k | nindent 6 }}
{{- end }}
{{- end }}
