{{- if .Values.controller.podDisruptionBudget -}}
---
{{- if .Capabilities.APIVersions.Has "policy/v1" -}}
apiVersion: policy/v1
{{ else }}
apiVersion: policy/v1beta1
{{- end -}}
kind: PodDisruptionBudget
metadata:
  name: {{ include "superblocks-agent.fullname" . }}
  labels:
    {{- include "superblocks-agent.labels" . | nindent 4 }}
    {{- include "superblocks-agent.controller.labels" . | nindent 4 }}
spec:
{{- .Values.controller.podDisruptionBudget | toYaml | nindent 2 }}
  selector:
    matchLabels:
      {{- include "superblocks-agent.selectorLabels" . | nindent 6 }}
      {{- include "superblocks-agent.controller.labels" . | nindent 6 }}
{{- end }}
