{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "superblocks-agent.fullname" . }}
  labels:
    {{- include "superblocks-agent.labels" . | nindent 4 }}
spec:
{{ .Values.podDisruptionBudget | toYaml | nindent 2 }}
  selector:
    matchLabels:
      {{- include "superblocks-agent.selectorLabels" . | nindent 6 }}
{{- end }}
