---
name: "Add Python Package"
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the python package to add, used in the pip install command."
        required: true
      version:
        description: "Version of the python package to add."
        required: false
        default: ""
      import_name:
        description: "The import name of the python package, if it differs from the name."
        required: false
        default: ""
env:
  REPO_PATH: "repo"
permissions:
  contents: write
  pull-requests: write
jobs:
  add-python-package:
    name: "Add Python Package"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: ${{ env.REPO_PATH }}
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Add package
        run: |
          cd ${{ env.REPO_PATH }}
          make add-package name=${{ github.event.inputs.name }} version=${{ github.event.inputs.version }} import_name=${{ github.event.inputs.import_name }}
      - name: Generate commit message
        id: commit_msg
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "msg=Add ${{ github.event.inputs.name }}==${{ github.event.inputs.version }}" >> "$GITHUB_OUTPUT"
          else
            echo "msg=Add ${{ github.event.inputs.name }}" >> "$GITHUB_OUTPUT"
          fi
      - name: Auto-generate pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ steps.commit_msg.outputs.msg }}
          title: ${{ steps.commit_msg.outputs.msg }}
          path: ${{ env.REPO_PATH }}
          add-paths: |
            requirements.txt
            src/speed.py
          body: |
            Auto-generated by [this Github workflow][1]

            [1]: https://github.com/superblocksteam/worker.py/blob/main/.github/workflows/add-package.yml
          signoff: false
          branch: add-package-${{ github.event.inputs.name }}
          delete-branch: true
          draft: false
