---
apiVersion: v3
name: worker_py
description: A Helm chart for the worker component of the Superblocks Agent Platform.
type: application
version: 0.0.1
appVersion: "latest"
dependencies:
  - name: redis
    version: 17.1.3
    repository: https://charts.bitnami.com/bitnami
    condition: queue.deploy
