root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "./worker-go --log.level=debug --emitter.remote.enabled=false --store.redis.password=dev-agent-key --transport.redis.password=dev-agent-key"
  cmd = "make build-go"
  delay = 1000
  exclude_dir = ["assets", "configs", "deploy", "scripts"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "json", "mod", "sum", "toml"]
  kill_delay = 2000
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
