---
version: "3.7"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: "--requirepass dev-agent-key"
  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
  kafka:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://kafka:9092,external://localhost:19092
    ports:
      - "18081:8081"
      - "18082:8082"
      - "19092:19092"
      - "9644:9644"
      - "9092:9092"
    networks:
      default:
        aliases:
          - kafka
  # NOTE(frank): It sucks that this service requires kafka and prostgres with no way to disable. Fix this.
  intake:
    image: ghcr.io/superblocksteam/intake:v0.88.0
    ports:
      - "10300:10300"
    environment:
      SUPERBLOCKS_INTAKE_KAFKA_BOOTSTRAP: kafka:9092
      SUPERBLOCKS_INTAKE_DB_URL: postgres://postgres:password@postgres:5432/postgres?sslmode=disable
      SUPERBLOCKS_INTAKE_HTTP_BIND: 0.0.0.0
    depends_on: [kafka, postgres]
  jaeger:
    image: jaegertracing/all-in-one:1.59
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "5778:5778"
      - "16686:16686" # This one is the UI.
      - "14268:14268"
      - "14250:14250"
      - "4317:4317"
      - "4318:4318"
volumes:
  postgres-data:
