// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IpFilterSetter is an autogenerated mock type for the IpFilterSetter type
type IpFilterSetter struct {
	mock.Mock
}

type IpFilterSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *IpFilterSetter) EXPECT() *IpFilterSetter_Expecter {
	return &IpFilterSetter_Expecter{mock: &_m.Mock}
}

// SetAllowedIps provides a mock function with given fields: ips
func (_m *IpFilterSetter) SetAllowedIps(ips ...string) {
	_va := make([]interface{}, len(ips))
	for _i := range ips {
		_va[_i] = ips[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// IpFilterSetter_SetAllowedIps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAllowedIps'
type IpFilterSetter_SetAllowedIps_Call struct {
	*mock.Call
}

// SetAllowedIps is a helper method to define mock.On call
//   - ips ...string
func (_e *IpFilterSetter_Expecter) SetAllowedIps(ips ...interface{}) *IpFilterSetter_SetAllowedIps_Call {
	return &IpFilterSetter_SetAllowedIps_Call{Call: _e.mock.On("SetAllowedIps",
		append([]interface{}{}, ips...)...)}
}

func (_c *IpFilterSetter_SetAllowedIps_Call) Run(run func(ips ...string)) *IpFilterSetter_SetAllowedIps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *IpFilterSetter_SetAllowedIps_Call) Return() *IpFilterSetter_SetAllowedIps_Call {
	_c.Call.Return()
	return _c
}

func (_c *IpFilterSetter_SetAllowedIps_Call) RunAndReturn(run func(...string)) *IpFilterSetter_SetAllowedIps_Call {
	_c.Run(run)
	return _c
}

// NewIpFilterSetter creates a new instance of IpFilterSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIpFilterSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *IpFilterSetter {
	mock := &IpFilterSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
