"use strict";
// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file plugins/databricks/v1/plugin.proto (package plugins.databricks.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.Plugin_DatabricksConnection = exports.Plugin = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
const plugin_pb_1 = require("../../common/v1/plugin_pb");
/**
 * @generated from message plugins.databricks.v1.Plugin
 */
class Plugin extends protobuf_1.Message {
    /**
     * @generated from field: string name = 1;
     */
    name = "";
    /**
     * @generated from field: plugins.databricks.v1.Plugin.DatabricksConnection connection = 2;
     */
    connection;
    /**
     * @generated from field: plugins.common.v1.SQLOperation operation = 3;
     */
    operation = plugin_pb_1.SQLOperation.SQL_OPERATION_UNSPECIFIED;
    /**
     * @generated from field: plugins.common.v1.SQLExecution run_sql = 4;
     */
    runSql;
    /**
     * @generated from field: plugins.common.v1.SQLBulkEdit bulk_edit = 5;
     */
    bulkEdit;
    /**
     * @generated from field: optional plugins.common.v1.DynamicWorkflowConfiguration dynamic_workflow_configuration = 6;
     */
    dynamicWorkflowConfiguration;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "plugins.databricks.v1.Plugin";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "connection", kind: "message", T: Plugin_DatabricksConnection },
        { no: 3, name: "operation", kind: "enum", T: protobuf_1.proto3.getEnumType(plugin_pb_1.SQLOperation) },
        { no: 4, name: "run_sql", kind: "message", T: plugin_pb_1.SQLExecution },
        { no: 5, name: "bulk_edit", kind: "message", T: plugin_pb_1.SQLBulkEdit },
        { no: 6, name: "dynamic_workflow_configuration", kind: "message", T: plugin_pb_1.DynamicWorkflowConfiguration, opt: true },
    ]);
    static fromBinary(bytes, options) {
        return new Plugin().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Plugin().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Plugin().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Plugin, a, b);
    }
}
exports.Plugin = Plugin;
/**
 * @generated from message plugins.databricks.v1.Plugin.DatabricksConnection
 */
class Plugin_DatabricksConnection extends protobuf_1.Message {
    /**
     * @generated from field: optional string default_catalog = 1;
     */
    defaultCatalog;
    /**
     * @generated from field: optional string default_schema = 2;
     */
    defaultSchema;
    /**
     * @generated from field: string host_url = 3;
     */
    hostUrl = "";
    /**
     * @generated from field: string path = 4;
     */
    path = "";
    /**
     * @generated from field: int32 port = 5;
     */
    port = 0;
    /**
     * @generated from field: string token = 6;
     */
    token = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "plugins.databricks.v1.Plugin.DatabricksConnection";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "default_catalog", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 2, name: "default_schema", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 3, name: "host_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 4, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 5, name: "port", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
        { no: 6, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new Plugin_DatabricksConnection().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Plugin_DatabricksConnection().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Plugin_DatabricksConnection().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Plugin_DatabricksConnection, a, b);
    }
}
exports.Plugin_DatabricksConnection = Plugin_DatabricksConnection;
//# sourceMappingURL=plugin_pb.map