"use strict";
// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file security/v1/service.proto (package security.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.VerifyResponse = exports.VerifyRequest = exports.SignResponse = exports.SignRequest = exports.Resource_ApiLiteral = exports.Resource_Literal = exports.Resource = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
const api_pb_1 = require("../../api/v1/api_pb");
const utils_pb_1 = require("../../utils/v1/utils_pb");
/**
 * @generated from message security.v1.Resource
 */
class Resource extends protobuf_1.Message {
    /**
     * @generated from oneof security.v1.Resource.config
     */
    config = { case: undefined };
    /**
     * @generated from oneof security.v1.Resource.git_ref
     */
    gitRef = { case: undefined };
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "security.v1.Resource";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "api", kind: "message", T: api_pb_1.Api, oneof: "config" },
        { no: 2, name: "literal", kind: "message", T: Resource_Literal, oneof: "config" },
        { no: 5, name: "api_literal", kind: "message", T: Resource_ApiLiteral, oneof: "config" },
        { no: 3, name: "commit_id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "git_ref" },
        { no: 4, name: "branch_name", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "git_ref" },
    ]);
    static fromBinary(bytes, options) {
        return new Resource().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Resource().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Resource().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Resource, a, b);
    }
}
exports.Resource = Resource;
/**
 * @generated from message security.v1.Resource.Literal
 */
class Resource_Literal extends protobuf_1.Message {
    /**
     * @generated from field: google.protobuf.Value data = 1;
     */
    data;
    /**
     * @generated from field: optional utils.v1.Signature signature = 2;
     */
    signature;
    /**
     * @generated from field: string resource_id = 3;
     */
    resourceId = "";
    /**
     * @generated from field: string organization_id = 4;
     */
    organizationId = "";
    /**
     * @generated from field: google.protobuf.Timestamp last_updated = 5;
     */
    lastUpdated;
    /**
     * @generated from field: string type = 6;
     */
    type = "";
    /**
     * @generated from field: int32 page_version = 7;
     */
    pageVersion = 0;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "security.v1.Resource.Literal";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "data", kind: "message", T: protobuf_1.Value },
        { no: 2, name: "signature", kind: "message", T: utils_pb_1.Signature, opt: true },
        { no: 3, name: "resource_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 4, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 5, name: "last_updated", kind: "message", T: protobuf_1.Timestamp },
        { no: 6, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 7, name: "page_version", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    ]);
    static fromBinary(bytes, options) {
        return new Resource_Literal().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Resource_Literal().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Resource_Literal().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Resource_Literal, a, b);
    }
}
exports.Resource_Literal = Resource_Literal;
/**
 * @generated from message security.v1.Resource.ApiLiteral
 */
class Resource_ApiLiteral extends protobuf_1.Message {
    /**
     * @generated from field: google.protobuf.Value data = 1;
     */
    data;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "security.v1.Resource.ApiLiteral";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "data", kind: "message", T: protobuf_1.Value },
    ]);
    static fromBinary(bytes, options) {
        return new Resource_ApiLiteral().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Resource_ApiLiteral().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Resource_ApiLiteral().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Resource_ApiLiteral, a, b);
    }
}
exports.Resource_ApiLiteral = Resource_ApiLiteral;
/**
 * @generated from message security.v1.SignRequest
 */
class SignRequest extends protobuf_1.Message {
    /**
     * @generated from field: security.v1.Resource resource = 1;
     */
    resource;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "security.v1.SignRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "resource", kind: "message", T: Resource },
    ]);
    static fromBinary(bytes, options) {
        return new SignRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new SignRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new SignRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(SignRequest, a, b);
    }
}
exports.SignRequest = SignRequest;
/**
 * @generated from message security.v1.SignResponse
 */
class SignResponse extends protobuf_1.Message {
    /**
     * @generated from field: utils.v1.Signature signature = 1;
     */
    signature;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "security.v1.SignResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "signature", kind: "message", T: utils_pb_1.Signature },
    ]);
    static fromBinary(bytes, options) {
        return new SignResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new SignResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new SignResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(SignResponse, a, b);
    }
}
exports.SignResponse = SignResponse;
/**
 * @generated from message security.v1.VerifyRequest
 */
class VerifyRequest extends protobuf_1.Message {
    /**
     * @generated from field: repeated security.v1.Resource resources = 1;
     */
    resources = [];
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "security.v1.VerifyRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "resources", kind: "message", T: Resource, repeated: true },
    ]);
    static fromBinary(bytes, options) {
        return new VerifyRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new VerifyRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new VerifyRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(VerifyRequest, a, b);
    }
}
exports.VerifyRequest = VerifyRequest;
/**
 * @generated from message security.v1.VerifyResponse
 */
class VerifyResponse extends protobuf_1.Message {
    /**
     * @generated from field: string key_id = 1;
     */
    keyId = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "security.v1.VerifyResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "key_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new VerifyResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new VerifyResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new VerifyResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(VerifyResponse, a, b);
    }
}
exports.VerifyResponse = VerifyResponse;
//# sourceMappingURL=service_pb.map