---
# Local testing configuration - uses host.docker.internal for Redis
# No password auth for Docker Redis
fleets:
  # Python ephemeral worker fleet
  python-ba:
    language: python
    bucket: BA
    consumerGroup: ephemeral-python
    streams:
      - agent.main.bucket.BA.ephemeral.plugin.python.event.execute
      - agent.main.bucket.BE.ephemeral.plugin.python.event.execute
      - agent.main.bucket.B1.ephemeral.plugin.python.event.execute
      - agent.main.bucket.B2.ephemeral.plugin.python.event.execute
    keda:
      pollingInterval: 1
      minReplicaCount: 1
      maxReplicaCount: 5
      triggers:
        - type: redis-streams
          metadata:
            address: host.docker.internal:6379
            stream: agent.main.bucket.BA.ephemeral.plugin.python.event.execute
            consumerGroup: ephemeral-python
            lagCount: "1"
          authenticationRef:
            name: redis-trigger-auth
  # JavaScript ephemeral worker fleet
  javascript-ba:
    language: javascript
    bucket: BA
    consumerGroup: ephemeral-javascript
    streams:
      - agent.main.bucket.BA.ephemeral.plugin.javascript.event.execute
      - agent.main.bucket.BE.ephemeral.plugin.javascript.event.execute
      - agent.main.bucket.B1.ephemeral.plugin.javascript.event.execute
      - agent.main.bucket.B2.ephemeral.plugin.javascript.event.execute
    keda:
      pollingInterval: 1
      minReplicaCount: 1
      maxReplicaCount: 5
      triggers:
        - type: redis-streams
          metadata:
            address: host.docker.internal:6379
            stream: agent.main.bucket.BA.ephemeral.plugin.javascript.event.execute
            consumerGroup: ephemeral-javascript
            lagCount: "1"
          authenticationRef:
            name: redis-trigger-auth
# Task Manager image
taskManager:
  image:
    repository: ghcr.io/superblocksteam/task-manager
    tag: latest
    pullPolicy: IfNotPresent
# Sandbox images
sandbox:
  python:
    image:
      repository: ghcr.io/superblocksteam/python-sandbox
      tag: latest
      pullPolicy: IfNotPresent
  javascript:
    image:
      repository: ghcr.io/superblocksteam/javascript-sandbox
      tag: latest
      pullPolicy: IfNotPresent
# Redis configuration - Docker Redis uses "koala" password
queue:
  host: host.docker.internal
  port: 6379
  tls: false
  password: koala
kvstore:
  host: host.docker.internal
  port: 6379
  tls: false
  password: koala
# Disable resource limits for local testing
nodeSelector: null
tolerations: null
affinity: null
# No image pull secrets for local images
imagePullSecrets: []
# Superblocks configuration
superblocks:
  key: dev-agent-key
