// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CapacityGate is an autogenerated mock type for the CapacityGate type
type CapacityGate struct {
	mock.Mock
}

type CapacityGate_Expecter struct {
	mock *mock.Mock
}

func (_m *CapacityGate) EXPECT() *CapacityGate_Expecter {
	return &CapacityGate_Expecter{mock: &_m.Mock}
}

// AcquireSlot provides a mock function with no fields
func (_m *CapacityGate) AcquireSlot() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AcquireSlot")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// CapacityGate_AcquireSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcquireSlot'
type CapacityGate_AcquireSlot_Call struct {
	*mock.Call
}

// AcquireSlot is a helper method to define mock.On call
func (_e *CapacityGate_Expecter) AcquireSlot() *CapacityGate_AcquireSlot_Call {
	return &CapacityGate_AcquireSlot_Call{Call: _e.mock.On("AcquireSlot")}
}

func (_c *CapacityGate_AcquireSlot_Call) Run(run func()) *CapacityGate_AcquireSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CapacityGate_AcquireSlot_Call) Return(_a0 string) *CapacityGate_AcquireSlot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CapacityGate_AcquireSlot_Call) RunAndReturn(run func() string) *CapacityGate_AcquireSlot_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseSlot provides a mock function with given fields: id
func (_m *CapacityGate) ReleaseSlot(id string) {
	_m.Called(id)
}

// CapacityGate_ReleaseSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseSlot'
type CapacityGate_ReleaseSlot_Call struct {
	*mock.Call
}

// ReleaseSlot is a helper method to define mock.On call
//   - id string
func (_e *CapacityGate_Expecter) ReleaseSlot(id interface{}) *CapacityGate_ReleaseSlot_Call {
	return &CapacityGate_ReleaseSlot_Call{Call: _e.mock.On("ReleaseSlot", id)}
}

func (_c *CapacityGate_ReleaseSlot_Call) Run(run func(id string)) *CapacityGate_ReleaseSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CapacityGate_ReleaseSlot_Call) Return() *CapacityGate_ReleaseSlot_Call {
	_c.Call.Return()
	return _c
}

func (_c *CapacityGate_ReleaseSlot_Call) RunAndReturn(run func(string)) *CapacityGate_ReleaseSlot_Call {
	_c.Run(run)
	return _c
}

// ReleaseUnusedSlot provides a mock function with no fields
func (_m *CapacityGate) ReleaseUnusedSlot() {
	_m.Called()
}

// CapacityGate_ReleaseUnusedSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseUnusedSlot'
type CapacityGate_ReleaseUnusedSlot_Call struct {
	*mock.Call
}

// ReleaseUnusedSlot is a helper method to define mock.On call
func (_e *CapacityGate_Expecter) ReleaseUnusedSlot() *CapacityGate_ReleaseUnusedSlot_Call {
	return &CapacityGate_ReleaseUnusedSlot_Call{Call: _e.mock.On("ReleaseUnusedSlot")}
}

func (_c *CapacityGate_ReleaseUnusedSlot_Call) Run(run func()) *CapacityGate_ReleaseUnusedSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CapacityGate_ReleaseUnusedSlot_Call) Return() *CapacityGate_ReleaseUnusedSlot_Call {
	_c.Call.Return()
	return _c
}

func (_c *CapacityGate_ReleaseUnusedSlot_Call) RunAndReturn(run func()) *CapacityGate_ReleaseUnusedSlot_Call {
	_c.Run(run)
	return _c
}

// NewCapacityGate creates a new instance of CapacityGate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCapacityGate(t interface {
	mock.TestingT
	Cleanup(func())
}) *CapacityGate {
	mock := &CapacityGate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
