// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	redis "github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"

	sync "sync"
)

// VariableStoreProvider is an autogenerated mock type for the VariableStoreProvider type
type VariableStoreProvider struct {
	mock.Mock
}

type VariableStoreProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *VariableStoreProvider) EXPECT() *VariableStoreProvider_Expecter {
	return &VariableStoreProvider_Expecter{mock: &_m.Mock}
}

// GetRedisClient provides a mock function with no fields
func (_m *VariableStoreProvider) GetRedisClient() *redis.Client {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRedisClient")
	}

	var r0 *redis.Client
	if rf, ok := ret.Get(0).(func() *redis.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.Client)
		}
	}

	return r0
}

// VariableStoreProvider_GetRedisClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRedisClient'
type VariableStoreProvider_GetRedisClient_Call struct {
	*mock.Call
}

// GetRedisClient is a helper method to define mock.On call
func (_e *VariableStoreProvider_Expecter) GetRedisClient() *VariableStoreProvider_GetRedisClient_Call {
	return &VariableStoreProvider_GetRedisClient_Call{Call: _e.mock.On("GetRedisClient")}
}

func (_c *VariableStoreProvider_GetRedisClient_Call) Run(run func()) *VariableStoreProvider_GetRedisClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VariableStoreProvider_GetRedisClient_Call) Return(_a0 *redis.Client) *VariableStoreProvider_GetRedisClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VariableStoreProvider_GetRedisClient_Call) RunAndReturn(run func() *redis.Client) *VariableStoreProvider_GetRedisClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetVariableStore provides a mock function with no fields
func (_m *VariableStoreProvider) GetVariableStore() map[string]map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVariableStore")
	}

	var r0 map[string]map[string]string
	if rf, ok := ret.Get(0).(func() map[string]map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]map[string]string)
		}
	}

	return r0
}

// VariableStoreProvider_GetVariableStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVariableStore'
type VariableStoreProvider_GetVariableStore_Call struct {
	*mock.Call
}

// GetVariableStore is a helper method to define mock.On call
func (_e *VariableStoreProvider_Expecter) GetVariableStore() *VariableStoreProvider_GetVariableStore_Call {
	return &VariableStoreProvider_GetVariableStore_Call{Call: _e.mock.On("GetVariableStore")}
}

func (_c *VariableStoreProvider_GetVariableStore_Call) Run(run func()) *VariableStoreProvider_GetVariableStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VariableStoreProvider_GetVariableStore_Call) Return(_a0 map[string]map[string]string) *VariableStoreProvider_GetVariableStore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VariableStoreProvider_GetVariableStore_Call) RunAndReturn(run func() map[string]map[string]string) *VariableStoreProvider_GetVariableStore_Call {
	_c.Call.Return(run)
	return _c
}

// GetVariableStoreLock provides a mock function with no fields
func (_m *VariableStoreProvider) GetVariableStoreLock() *sync.RWMutex {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVariableStoreLock")
	}

	var r0 *sync.RWMutex
	if rf, ok := ret.Get(0).(func() *sync.RWMutex); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sync.RWMutex)
		}
	}

	return r0
}

// VariableStoreProvider_GetVariableStoreLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVariableStoreLock'
type VariableStoreProvider_GetVariableStoreLock_Call struct {
	*mock.Call
}

// GetVariableStoreLock is a helper method to define mock.On call
func (_e *VariableStoreProvider_Expecter) GetVariableStoreLock() *VariableStoreProvider_GetVariableStoreLock_Call {
	return &VariableStoreProvider_GetVariableStoreLock_Call{Call: _e.mock.On("GetVariableStoreLock")}
}

func (_c *VariableStoreProvider_GetVariableStoreLock_Call) Run(run func()) *VariableStoreProvider_GetVariableStoreLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VariableStoreProvider_GetVariableStoreLock_Call) Return(_a0 *sync.RWMutex) *VariableStoreProvider_GetVariableStoreLock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VariableStoreProvider_GetVariableStoreLock_Call) RunAndReturn(run func() *sync.RWMutex) *VariableStoreProvider_GetVariableStoreLock_Call {
	_c.Call.Return(run)
	return _c
}

// NewVariableStoreProvider creates a new instance of VariableStoreProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVariableStoreProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *VariableStoreProvider {
	mock := &VariableStoreProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
