"use strict";
// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file syncer/v1/service.proto (package syncer.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeleteMetadataResponse = exports.DeleteMetadataRequest = exports.UpsertMetadataResponse = exports.UpsertMetadataRequest = exports.SyncResponse_Integration = exports.SyncResponse = exports.SyncRequest = exports.GetConfigurationMetadataResponse = exports.GetConfigurationMetadataRequest = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
const errors_pb_1 = require("../../common/v1/errors_pb");
const syncer_pb_1 = require("./syncer_pb");
/**
 * @generated from message syncer.v1.GetConfigurationMetadataRequest
 */
class GetConfigurationMetadataRequest extends protobuf_1.Message {
    /**
     * @generated from field: string integration_id = 1;
     */
    integrationId = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "syncer.v1.GetConfigurationMetadataRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "integration_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new GetConfigurationMetadataRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GetConfigurationMetadataRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GetConfigurationMetadataRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(GetConfigurationMetadataRequest, a, b);
    }
}
exports.GetConfigurationMetadataRequest = GetConfigurationMetadataRequest;
/**
 * @generated from message syncer.v1.GetConfigurationMetadataResponse
 */
class GetConfigurationMetadataResponse extends protobuf_1.Message {
    /**
     * @generated from field: string integration_id = 1;
     */
    integrationId = "";
    /**
     * @generated from field: map<string, google.protobuf.Struct> configurations = 2;
     */
    configurations = {};
    /**
     * @generated from field: string integration_type = 3;
     */
    integrationType = "";
    /**
     * @generated from field: string organization_id = 4;
     */
    organizationId = "";
    /**
     * @generated from field: repeated common.v1.Error errors = 5;
     */
    errors = [];
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "syncer.v1.GetConfigurationMetadataResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "integration_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "configurations", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "message", T: protobuf_1.Struct } },
        { no: 3, name: "integration_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 4, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 5, name: "errors", kind: "message", T: errors_pb_1.Error, repeated: true },
    ]);
    static fromBinary(bytes, options) {
        return new GetConfigurationMetadataResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GetConfigurationMetadataResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GetConfigurationMetadataResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(GetConfigurationMetadataResponse, a, b);
    }
}
exports.GetConfigurationMetadataResponse = GetConfigurationMetadataResponse;
/**
 * @generated from message syncer.v1.SyncRequest
 */
class SyncRequest extends protobuf_1.Message {
    /**
     * @generated from field: repeated string integration_ids = 1;
     */
    integrationIds = [];
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "syncer.v1.SyncRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "integration_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    ]);
    static fromBinary(bytes, options) {
        return new SyncRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new SyncRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new SyncRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(SyncRequest, a, b);
    }
}
exports.SyncRequest = SyncRequest;
/**
 * @generated from message syncer.v1.SyncResponse
 */
class SyncResponse extends protobuf_1.Message {
    /**
     * @generated from field: map<string, syncer.v1.SyncResponse.Integration> integrations_synced = 1;
     */
    integrationsSynced = {};
    /**
     * @generated from field: repeated common.v1.Error errors = 2;
     */
    errors = [];
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "syncer.v1.SyncResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "integrations_synced", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "message", T: SyncResponse_Integration } },
        { no: 2, name: "errors", kind: "message", T: errors_pb_1.Error, repeated: true },
    ]);
    static fromBinary(bytes, options) {
        return new SyncResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new SyncResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new SyncResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(SyncResponse, a, b);
    }
}
exports.SyncResponse = SyncResponse;
/**
 * @generated from message syncer.v1.SyncResponse.Integration
 */
class SyncResponse_Integration extends protobuf_1.Message {
    /**
     * @generated from field: repeated string configurationIds = 1;
     */
    configurationIds = [];
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "syncer.v1.SyncResponse.Integration";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "configurationIds", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    ]);
    static fromBinary(bytes, options) {
        return new SyncResponse_Integration().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new SyncResponse_Integration().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new SyncResponse_Integration().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(SyncResponse_Integration, a, b);
    }
}
exports.SyncResponse_Integration = SyncResponse_Integration;
/**
 * @generated from message syncer.v1.UpsertMetadataRequest
 */
class UpsertMetadataRequest extends protobuf_1.Message {
    /**
     * @generated from field: repeated syncer.v1.Metadata metadata = 1;
     */
    metadata = [];
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "syncer.v1.UpsertMetadataRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "metadata", kind: "message", T: syncer_pb_1.Metadata, repeated: true },
    ]);
    static fromBinary(bytes, options) {
        return new UpsertMetadataRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UpsertMetadataRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UpsertMetadataRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UpsertMetadataRequest, a, b);
    }
}
exports.UpsertMetadataRequest = UpsertMetadataRequest;
/**
 * @generated from message syncer.v1.UpsertMetadataResponse
 */
class UpsertMetadataResponse extends protobuf_1.Message {
    /**
     * @generated from field: repeated common.v1.Error errors = 1;
     */
    errors = [];
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "syncer.v1.UpsertMetadataResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "errors", kind: "message", T: errors_pb_1.Error, repeated: true },
    ]);
    static fromBinary(bytes, options) {
        return new UpsertMetadataResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UpsertMetadataResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UpsertMetadataResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UpsertMetadataResponse, a, b);
    }
}
exports.UpsertMetadataResponse = UpsertMetadataResponse;
/**
 * @generated from message syncer.v1.DeleteMetadataRequest
 */
class DeleteMetadataRequest extends protobuf_1.Message {
    /**
     * @generated from field: string integration_id = 1;
     */
    integrationId = "";
    /**
     * @generated from field: repeated string configuration_ids = 2;
     */
    configurationIds = [];
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "syncer.v1.DeleteMetadataRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "integration_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "configuration_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    ]);
    static fromBinary(bytes, options) {
        return new DeleteMetadataRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new DeleteMetadataRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new DeleteMetadataRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(DeleteMetadataRequest, a, b);
    }
}
exports.DeleteMetadataRequest = DeleteMetadataRequest;
/**
 * @generated from message syncer.v1.DeleteMetadataResponse
 */
class DeleteMetadataResponse extends protobuf_1.Message {
    /**
     * @generated from field: repeated common.v1.Error errors = 1;
     */
    errors = [];
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "syncer.v1.DeleteMetadataResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "errors", kind: "message", T: errors_pb_1.Error, repeated: true },
    ]);
    static fromBinary(bytes, options) {
        return new DeleteMetadataResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new DeleteMetadataResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new DeleteMetadataResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(DeleteMetadataResponse, a, b);
    }
}
exports.DeleteMetadataResponse = DeleteMetadataResponse;
//# sourceMappingURL=service_pb.map