apiVersion: v1
kind: Service
metadata:
  name: {{ include "superblocks-agent.fullname" . }}
  labels:
    {{- include "superblocks-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
  - port: {{ .Values.controller.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "superblocks-agent.selectorLabels" . | nindent 4 }}
