{{- if .Values.externalSecrets.enabled }}
{{- $fullname := include "sandbox_workers.fullname" . }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-worker-agent-key" $fullname | trunc 63 | trimSuffix "-" }}
  annotations:
    external-secrets.io/force-sync: {{ now | date "2006-01-02T15:04:05Z" | quote }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ printf "%s-worker-agent-key" $fullname | trunc 63 | trimSuffix "-" }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.agentKey.data | nindent 4 }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-worker-queue-redis-token" $fullname | trunc 63 | trimSuffix "-" }}
  annotations:
    external-secrets.io/force-sync: {{ now | date "2006-01-02T15:04:05Z" | quote }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ printf "%s-worker-queue-redis-token" $fullname | trunc 63 | trimSuffix "-" }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.queueRedis.data | nindent 4 }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-worker-kvstore-redis-token" $fullname | trunc 63 | trimSuffix "-" }}
  annotations:
    external-secrets.io/force-sync: {{ now | date "2006-01-02T15:04:05Z" | quote }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ printf "%s-worker-kvstore-redis-token" $fullname | trunc 63 | trimSuffix "-" }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.kvstoreRedis.data | nindent 4 }}
{{- end }}
