"use strict";
// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file secrets/v1/secrets.proto (package secrets.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.Invalidation = exports.Details = exports.Store = exports.Provider = exports.MockStore = exports.HashicorpVault_Auth_AppRole = exports.HashicorpVault_Auth = exports.HashicorpVault_Version = exports.HashicorpVault = exports.AkeylessSecretsManager = exports.GcpSecretManager = exports.AwsSecretsManager = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
const auth_pb_1 = require("../../plugins/common/v1/auth_pb");
const common_pb_1 = require("../../common/v1/common_pb");
/**
 * @generated from message secrets.v1.AwsSecretsManager
 */
class AwsSecretsManager extends protobuf_1.Message {
    /**
     * @generated from field: plugins.common.v1.AwsAuth auth = 1;
     */
    auth;
    /**
     * @generated from field: optional string prefix = 2;
     */
    prefix;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "secrets.v1.AwsSecretsManager";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "auth", kind: "message", T: auth_pb_1.AwsAuth },
        { no: 2, name: "prefix", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    ]);
    static fromBinary(bytes, options) {
        return new AwsSecretsManager().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new AwsSecretsManager().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new AwsSecretsManager().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(AwsSecretsManager, a, b);
    }
}
exports.AwsSecretsManager = AwsSecretsManager;
/**
 * @generated from message secrets.v1.GcpSecretManager
 */
class GcpSecretManager extends protobuf_1.Message {
    /**
     * @generated from field: plugins.common.v1.GcpAuth auth = 1;
     */
    auth;
    /**
     * @generated from field: string project_id = 2;
     */
    projectId = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "secrets.v1.GcpSecretManager";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "auth", kind: "message", T: auth_pb_1.GcpAuth },
        { no: 2, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new GcpSecretManager().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GcpSecretManager().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GcpSecretManager().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(GcpSecretManager, a, b);
    }
}
exports.GcpSecretManager = GcpSecretManager;
/**
 * @generated from message secrets.v1.AkeylessSecretsManager
 */
class AkeylessSecretsManager extends protobuf_1.Message {
    /**
     * @generated from field: plugins.common.v1.AkeylessAuth auth = 1;
     */
    auth;
    /**
     * @generated from field: optional string host = 2;
     */
    host;
    /**
     * @generated from field: optional string prefix = 3;
     */
    prefix;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "secrets.v1.AkeylessSecretsManager";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "auth", kind: "message", T: auth_pb_1.AkeylessAuth },
        { no: 2, name: "host", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 3, name: "prefix", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    ]);
    static fromBinary(bytes, options) {
        return new AkeylessSecretsManager().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new AkeylessSecretsManager().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new AkeylessSecretsManager().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(AkeylessSecretsManager, a, b);
    }
}
exports.AkeylessSecretsManager = AkeylessSecretsManager;
/**
 * @generated from message secrets.v1.HashicorpVault
 */
class HashicorpVault extends protobuf_1.Message {
    /**
     * @generated from field: secrets.v1.HashicorpVault.Auth auth = 1;
     */
    auth;
    /**
     * The location of the vault server.
     *
     * @generated from field: string address = 2;
     */
    address = "";
    /**
     * The path to the vault
     *
     * @generated from field: optional string path = 3;
     */
    path;
    /**
     * The Hashicorp Vault namespace.
     *
     * @generated from field: optional string namespace = 4;
     */
    namespace;
    /**
     * The engine version.
     *
     * @generated from field: secrets.v1.HashicorpVault.Version version = 5;
     */
    version = HashicorpVault_Version.UNSPECIFIED;
    /**
     * the path to the secrets
     *
     * @generated from field: optional string secrets_path = 6;
     */
    secretsPath;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "secrets.v1.HashicorpVault";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "auth", kind: "message", T: HashicorpVault_Auth },
        { no: 2, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 4, name: "namespace", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 5, name: "version", kind: "enum", T: protobuf_1.proto3.getEnumType(HashicorpVault_Version) },
        { no: 6, name: "secrets_path", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    ]);
    static fromBinary(bytes, options) {
        return new HashicorpVault().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new HashicorpVault().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new HashicorpVault().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(HashicorpVault, a, b);
    }
}
exports.HashicorpVault = HashicorpVault;
/**
 * @generated from enum secrets.v1.HashicorpVault.Version
 */
var HashicorpVault_Version;
(function (HashicorpVault_Version) {
    /**
     * @generated from enum value: VERSION_UNSPECIFIED = 0;
     */
    HashicorpVault_Version[HashicorpVault_Version["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    /**
     * @generated from enum value: VERSION_V1 = 1;
     */
    HashicorpVault_Version[HashicorpVault_Version["V1"] = 1] = "V1";
    /**
     * @generated from enum value: VERSION_V2 = 2;
     */
    HashicorpVault_Version[HashicorpVault_Version["V2"] = 2] = "V2";
})(HashicorpVault_Version || (exports.HashicorpVault_Version = HashicorpVault_Version = {}));
// Retrieve enum metadata with: proto3.getEnumType(HashicorpVault_Version)
protobuf_1.proto3.util.setEnumType(HashicorpVault_Version, "secrets.v1.HashicorpVault.Version", [
    { no: 0, name: "VERSION_UNSPECIFIED" },
    { no: 1, name: "VERSION_V1" },
    { no: 2, name: "VERSION_V2" },
]);
/**
 * @generated from message secrets.v1.HashicorpVault.Auth
 */
class HashicorpVault_Auth extends protobuf_1.Message {
    /**
     * @generated from oneof secrets.v1.HashicorpVault.Auth.config
     */
    config = { case: undefined };
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "secrets.v1.HashicorpVault.Auth";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "config" },
        { no: 2, name: "app_role", kind: "message", T: HashicorpVault_Auth_AppRole, oneof: "config" },
    ]);
    static fromBinary(bytes, options) {
        return new HashicorpVault_Auth().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new HashicorpVault_Auth().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new HashicorpVault_Auth().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(HashicorpVault_Auth, a, b);
    }
}
exports.HashicorpVault_Auth = HashicorpVault_Auth;
/**
 * @generated from message secrets.v1.HashicorpVault.Auth.AppRole
 */
class HashicorpVault_Auth_AppRole extends protobuf_1.Message {
    /**
     * @generated from field: string role_id = 1;
     */
    roleId = "";
    /**
     * @generated from field: string secret_id = 2;
     */
    secretId = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "secrets.v1.HashicorpVault.Auth.AppRole";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "role_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "secret_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new HashicorpVault_Auth_AppRole().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new HashicorpVault_Auth_AppRole().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new HashicorpVault_Auth_AppRole().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(HashicorpVault_Auth_AppRole, a, b);
    }
}
exports.HashicorpVault_Auth_AppRole = HashicorpVault_Auth_AppRole;
/**
 * @generated from message secrets.v1.MockStore
 */
class MockStore extends protobuf_1.Message {
    /**
     * @generated from field: map<string, string> data = 1;
     */
    data = {};
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "secrets.v1.MockStore";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "data", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "scalar", T: 9 /* ScalarType.STRING */ } },
    ]);
    static fromBinary(bytes, options) {
        return new MockStore().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new MockStore().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new MockStore().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(MockStore, a, b);
    }
}
exports.MockStore = MockStore;
/**
 * @generated from message secrets.v1.Provider
 */
class Provider extends protobuf_1.Message {
    /**
     * @generated from oneof secrets.v1.Provider.config
     */
    config = { case: undefined };
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "secrets.v1.Provider";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "mock", kind: "message", T: MockStore, oneof: "config" },
        { no: 2, name: "akeyless_secrets_manager", kind: "message", T: AkeylessSecretsManager, oneof: "config" },
        { no: 3, name: "aws_secrets_manager", kind: "message", T: AwsSecretsManager, oneof: "config" },
        { no: 4, name: "gcp_secret_manager", kind: "message", T: GcpSecretManager, oneof: "config" },
        { no: 5, name: "hashicorp_vault", kind: "message", T: HashicorpVault, oneof: "config" },
    ]);
    static fromBinary(bytes, options) {
        return new Provider().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Provider().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Provider().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Provider, a, b);
    }
}
exports.Provider = Provider;
/**
 * @generated from message secrets.v1.Store
 */
class Store extends protobuf_1.Message {
    /**
     * @generated from field: common.v1.Metadata metadata = 1;
     */
    metadata;
    /**
     * @generated from field: secrets.v1.Provider provider = 2;
     */
    provider;
    /**
     * @generated from field: optional int32 ttl = 3;
     */
    ttl;
    /**
     * @generated from field: string configuration_id = 4;
     */
    configurationId = "";
    /**
     * @generated from field: bool cache = 5;
     */
    cache = false;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "secrets.v1.Store";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "metadata", kind: "message", T: common_pb_1.Metadata },
        { no: 2, name: "provider", kind: "message", T: Provider },
        { no: 3, name: "ttl", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
        { no: 4, name: "configuration_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 5, name: "cache", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    ]);
    static fromBinary(bytes, options) {
        return new Store().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Store().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Store().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Store, a, b);
    }
}
exports.Store = Store;
/**
 * Details represents the details of a secret.
 * It does not contain the value.
 *
 * @generated from message secrets.v1.Details
 */
class Details extends protobuf_1.Message {
    /**
     * i.e. "foo"
     *
     * @generated from field: string alias = 1;
     */
    alias = "";
    /**
     * i.e. "/projects/my-project/secrets/foo/versions/1"
     *
     * @generated from field: string name = 2;
     */
    name = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "secrets.v1.Details";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "alias", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new Details().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Details().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Details().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Details, a, b);
    }
}
exports.Details = Details;
/**
 * @generated from message secrets.v1.Invalidation
 */
class Invalidation extends protobuf_1.Message {
    /**
     * @generated from field: string alias = 1;
     */
    alias = "";
    /**
     * @generated from field: string configuration_id = 2;
     */
    configurationId = "";
    /**
     * @generated from field: string store = 3;
     */
    store = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "secrets.v1.Invalidation";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "alias", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "configuration_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "store", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new Invalidation().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Invalidation().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Invalidation().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Invalidation, a, b);
    }
}
exports.Invalidation = Invalidation;
//# sourceMappingURL=secrets_pb.map