#!/command/with-contenv sh

export SUPERBLOCKS_AGENT_KEY="${SB_AGENT_KEY:-${SUPERBLOCKS_AGENT_KEY}}"
export SUPERBLOCKS_WORKER_EXECUTION_ENV_INCLUSION_LIST="${SB_EXECUTION_ENV_INCLUSION_LIST:-${SUPERBLOCKS_EXECUTION_ENV_INCLUSION_LIST}}"
export SB_METRICS_PORT=19090

echo "{\"level\":\"info\",\"ts\":$(date +%s%3N),\"msg\":\"starting component worker.py\",\"component\":\"s6\"}"
python3 /app/worker.py/src/entry.py
