FROM python:3.10.1

WORKDIR /app

# install some global dependencies
RUN apt-get update && apt-get install -y cmake libblas-dev liblapack-dev && python -m pip install --no-cache-dir cython

# install existing deps
COPY requirements.txt .
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
RUN uv pip install --system --no-cache-dir -r requirements.txt

# argument for additional dependency
ARG ADDITIONAL_DEP

# run additional install
RUN uv pip install --system --no-cache-dir ${ADDITIONAL_DEP}

# update requirements file
RUN pip freeze > requirements.txt

# keep container running so we can yeet the requirements file
CMD ["tail", "-f", "/dev/null"]

