ARG UV_VERSION=0.11.15
FROM ghcr.io/astral-sh/uv:${UV_VERSION} AS uv
FROM python:3.10.1

WORKDIR /app

# install some global dependencies
RUN apt-get update && apt-get install -y cmake libblas-dev liblapack-dev && python -m pip install --no-cache-dir cython

ARG REQUIREMENTS_FILE=requirements.txt

# install existing deps
COPY ${REQUIREMENTS_FILE} .
COPY --from=uv /uv /uvx /bin/
RUN uv pip install --system --no-cache-dir -r ${REQUIREMENTS_FILE}

# argument for additional dependency
ARG ADDITIONAL_DEP

# run additional install
RUN uv pip install --system --no-cache-dir ${ADDITIONAL_DEP}

# update requirements file
RUN pip freeze > ${REQUIREMENTS_FILE}

# keep container running so we can yeet the requirements file
CMD ["tail", "-f", "/dev/null"]

