// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	structpb "google.golang.org/protobuf/types/known/structpb"

	transportv1 "github.com/superblocksteam/agent/types/gen/go/transport/v1"

	v1 "github.com/superblocksteam/agent/types/gen/go/worker/v1"
)

// JavascriptPlugin is an autogenerated mock type for the JavascriptPlugin type
type JavascriptPlugin struct {
	mock.Mock
}

type JavascriptPlugin_Expecter struct {
	mock *mock.Mock
}

func (_m *JavascriptPlugin) EXPECT() *JavascriptPlugin_Expecter {
	return &JavascriptPlugin_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, requestMeta, requestProps, quotas, pinned
func (_m *JavascriptPlugin) Execute(ctx context.Context, requestMeta *v1.RequestMetadata, requestProps *transportv1.Request_Data_Data_Props, quotas *transportv1.Request_Data_Data_Quota, pinned *transportv1.Request_Data_Pinned) (*v1.ExecuteResponse, error) {
	ret := _m.Called(ctx, requestMeta, requestProps, quotas, pinned)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *v1.ExecuteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.RequestMetadata, *transportv1.Request_Data_Data_Props, *transportv1.Request_Data_Data_Quota, *transportv1.Request_Data_Pinned) (*v1.ExecuteResponse, error)); ok {
		return rf(ctx, requestMeta, requestProps, quotas, pinned)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.RequestMetadata, *transportv1.Request_Data_Data_Props, *transportv1.Request_Data_Data_Quota, *transportv1.Request_Data_Pinned) *v1.ExecuteResponse); ok {
		r0 = rf(ctx, requestMeta, requestProps, quotas, pinned)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ExecuteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.RequestMetadata, *transportv1.Request_Data_Data_Props, *transportv1.Request_Data_Data_Quota, *transportv1.Request_Data_Pinned) error); ok {
		r1 = rf(ctx, requestMeta, requestProps, quotas, pinned)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JavascriptPlugin_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type JavascriptPlugin_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - requestMeta *v1.RequestMetadata
//   - requestProps *transportv1.Request_Data_Data_Props
//   - quotas *transportv1.Request_Data_Data_Quota
//   - pinned *transportv1.Request_Data_Pinned
func (_e *JavascriptPlugin_Expecter) Execute(ctx interface{}, requestMeta interface{}, requestProps interface{}, quotas interface{}, pinned interface{}) *JavascriptPlugin_Execute_Call {
	return &JavascriptPlugin_Execute_Call{Call: _e.mock.On("Execute", ctx, requestMeta, requestProps, quotas, pinned)}
}

func (_c *JavascriptPlugin_Execute_Call) Run(run func(ctx context.Context, requestMeta *v1.RequestMetadata, requestProps *transportv1.Request_Data_Data_Props, quotas *transportv1.Request_Data_Data_Quota, pinned *transportv1.Request_Data_Pinned)) *JavascriptPlugin_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.RequestMetadata), args[2].(*transportv1.Request_Data_Data_Props), args[3].(*transportv1.Request_Data_Data_Quota), args[4].(*transportv1.Request_Data_Pinned))
	})
	return _c
}

func (_c *JavascriptPlugin_Execute_Call) Return(_a0 *v1.ExecuteResponse, _a1 error) *JavascriptPlugin_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JavascriptPlugin_Execute_Call) RunAndReturn(run func(context.Context, *v1.RequestMetadata, *transportv1.Request_Data_Data_Props, *transportv1.Request_Data_Data_Quota, *transportv1.Request_Data_Pinned) (*v1.ExecuteResponse, error)) *JavascriptPlugin_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function with given fields: ctx, requestMeta, datasourceConfig, actionConfig
func (_m *JavascriptPlugin) Metadata(ctx context.Context, requestMeta *v1.RequestMetadata, datasourceConfig *structpb.Struct, actionConfig *structpb.Struct) (*transportv1.Response_Data_Data, error) {
	ret := _m.Called(ctx, requestMeta, datasourceConfig, actionConfig)

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 *transportv1.Response_Data_Data
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.RequestMetadata, *structpb.Struct, *structpb.Struct) (*transportv1.Response_Data_Data, error)); ok {
		return rf(ctx, requestMeta, datasourceConfig, actionConfig)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.RequestMetadata, *structpb.Struct, *structpb.Struct) *transportv1.Response_Data_Data); ok {
		r0 = rf(ctx, requestMeta, datasourceConfig, actionConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transportv1.Response_Data_Data)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.RequestMetadata, *structpb.Struct, *structpb.Struct) error); ok {
		r1 = rf(ctx, requestMeta, datasourceConfig, actionConfig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JavascriptPlugin_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type JavascriptPlugin_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
//   - ctx context.Context
//   - requestMeta *v1.RequestMetadata
//   - datasourceConfig *structpb.Struct
//   - actionConfig *structpb.Struct
func (_e *JavascriptPlugin_Expecter) Metadata(ctx interface{}, requestMeta interface{}, datasourceConfig interface{}, actionConfig interface{}) *JavascriptPlugin_Metadata_Call {
	return &JavascriptPlugin_Metadata_Call{Call: _e.mock.On("Metadata", ctx, requestMeta, datasourceConfig, actionConfig)}
}

func (_c *JavascriptPlugin_Metadata_Call) Run(run func(ctx context.Context, requestMeta *v1.RequestMetadata, datasourceConfig *structpb.Struct, actionConfig *structpb.Struct)) *JavascriptPlugin_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.RequestMetadata), args[2].(*structpb.Struct), args[3].(*structpb.Struct))
	})
	return _c
}

func (_c *JavascriptPlugin_Metadata_Call) Return(_a0 *transportv1.Response_Data_Data, _a1 error) *JavascriptPlugin_Metadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JavascriptPlugin_Metadata_Call) RunAndReturn(run func(context.Context, *v1.RequestMetadata, *structpb.Struct, *structpb.Struct) (*transportv1.Response_Data_Data, error)) *JavascriptPlugin_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// PreDelete provides a mock function with given fields: ctx, requestMeta, datasourceConfig
func (_m *JavascriptPlugin) PreDelete(ctx context.Context, requestMeta *v1.RequestMetadata, datasourceConfig *structpb.Struct) error {
	ret := _m.Called(ctx, requestMeta, datasourceConfig)

	if len(ret) == 0 {
		panic("no return value specified for PreDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.RequestMetadata, *structpb.Struct) error); ok {
		r0 = rf(ctx, requestMeta, datasourceConfig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// JavascriptPlugin_PreDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreDelete'
type JavascriptPlugin_PreDelete_Call struct {
	*mock.Call
}

// PreDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - requestMeta *v1.RequestMetadata
//   - datasourceConfig *structpb.Struct
func (_e *JavascriptPlugin_Expecter) PreDelete(ctx interface{}, requestMeta interface{}, datasourceConfig interface{}) *JavascriptPlugin_PreDelete_Call {
	return &JavascriptPlugin_PreDelete_Call{Call: _e.mock.On("PreDelete", ctx, requestMeta, datasourceConfig)}
}

func (_c *JavascriptPlugin_PreDelete_Call) Run(run func(ctx context.Context, requestMeta *v1.RequestMetadata, datasourceConfig *structpb.Struct)) *JavascriptPlugin_PreDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.RequestMetadata), args[2].(*structpb.Struct))
	})
	return _c
}

func (_c *JavascriptPlugin_PreDelete_Call) Return(_a0 error) *JavascriptPlugin_PreDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JavascriptPlugin_PreDelete_Call) RunAndReturn(run func(context.Context, *v1.RequestMetadata, *structpb.Struct) error) *JavascriptPlugin_PreDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Stream provides a mock function with given fields: ctx, topic, requestMeta, requestProps, quotas, pinned
func (_m *JavascriptPlugin) Stream(ctx context.Context, topic string, requestMeta *v1.RequestMetadata, requestProps *transportv1.Request_Data_Data_Props, quotas *transportv1.Request_Data_Data_Quota, pinned *transportv1.Request_Data_Pinned) error {
	ret := _m.Called(ctx, topic, requestMeta, requestProps, quotas, pinned)

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1.RequestMetadata, *transportv1.Request_Data_Data_Props, *transportv1.Request_Data_Data_Quota, *transportv1.Request_Data_Pinned) error); ok {
		r0 = rf(ctx, topic, requestMeta, requestProps, quotas, pinned)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// JavascriptPlugin_Stream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stream'
type JavascriptPlugin_Stream_Call struct {
	*mock.Call
}

// Stream is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - requestMeta *v1.RequestMetadata
//   - requestProps *transportv1.Request_Data_Data_Props
//   - quotas *transportv1.Request_Data_Data_Quota
//   - pinned *transportv1.Request_Data_Pinned
func (_e *JavascriptPlugin_Expecter) Stream(ctx interface{}, topic interface{}, requestMeta interface{}, requestProps interface{}, quotas interface{}, pinned interface{}) *JavascriptPlugin_Stream_Call {
	return &JavascriptPlugin_Stream_Call{Call: _e.mock.On("Stream", ctx, topic, requestMeta, requestProps, quotas, pinned)}
}

func (_c *JavascriptPlugin_Stream_Call) Run(run func(ctx context.Context, topic string, requestMeta *v1.RequestMetadata, requestProps *transportv1.Request_Data_Data_Props, quotas *transportv1.Request_Data_Data_Quota, pinned *transportv1.Request_Data_Pinned)) *JavascriptPlugin_Stream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1.RequestMetadata), args[3].(*transportv1.Request_Data_Data_Props), args[4].(*transportv1.Request_Data_Data_Quota), args[5].(*transportv1.Request_Data_Pinned))
	})
	return _c
}

func (_c *JavascriptPlugin_Stream_Call) Return(_a0 error) *JavascriptPlugin_Stream_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JavascriptPlugin_Stream_Call) RunAndReturn(run func(context.Context, string, *v1.RequestMetadata, *transportv1.Request_Data_Data_Props, *transportv1.Request_Data_Data_Quota, *transportv1.Request_Data_Pinned) error) *JavascriptPlugin_Stream_Call {
	_c.Call.Return(run)
	return _c
}

// Test provides a mock function with given fields: ctx, requestMeta, datasourceConfig, actionConfig
func (_m *JavascriptPlugin) Test(ctx context.Context, requestMeta *v1.RequestMetadata, datasourceConfig *structpb.Struct, actionConfig *structpb.Struct) error {
	ret := _m.Called(ctx, requestMeta, datasourceConfig, actionConfig)

	if len(ret) == 0 {
		panic("no return value specified for Test")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.RequestMetadata, *structpb.Struct, *structpb.Struct) error); ok {
		r0 = rf(ctx, requestMeta, datasourceConfig, actionConfig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// JavascriptPlugin_Test_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Test'
type JavascriptPlugin_Test_Call struct {
	*mock.Call
}

// Test is a helper method to define mock.On call
//   - ctx context.Context
//   - requestMeta *v1.RequestMetadata
//   - datasourceConfig *structpb.Struct
//   - actionConfig *structpb.Struct
func (_e *JavascriptPlugin_Expecter) Test(ctx interface{}, requestMeta interface{}, datasourceConfig interface{}, actionConfig interface{}) *JavascriptPlugin_Test_Call {
	return &JavascriptPlugin_Test_Call{Call: _e.mock.On("Test", ctx, requestMeta, datasourceConfig, actionConfig)}
}

func (_c *JavascriptPlugin_Test_Call) Run(run func(ctx context.Context, requestMeta *v1.RequestMetadata, datasourceConfig *structpb.Struct, actionConfig *structpb.Struct)) *JavascriptPlugin_Test_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.RequestMetadata), args[2].(*structpb.Struct), args[3].(*structpb.Struct))
	})
	return _c
}

func (_c *JavascriptPlugin_Test_Call) Return(_a0 error) *JavascriptPlugin_Test_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JavascriptPlugin_Test_Call) RunAndReturn(run func(context.Context, *v1.RequestMetadata, *structpb.Struct, *structpb.Struct) error) *JavascriptPlugin_Test_Call {
	_c.Call.Return(run)
	return _c
}

// NewJavascriptPlugin creates a new instance of JavascriptPlugin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJavascriptPlugin(t interface {
	mock.TestingT
	Cleanup(func())
}) *JavascriptPlugin {
	mock := &JavascriptPlugin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
