import { EnvStore } from '@superblocks/shared';
import dotenv from 'dotenv';

dotenv.config();

const envs = new EnvStore(process.env);

envs.addAll([
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_LOG_LEVEL',
    defaultValue: 'info'
  },
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_PORT',
    defaultValue: '50051'
  },
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_VARIABLE_STORE_ADDRESS',
    defaultValue: 'localhost:50050'
  },
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_VARIABLE_STORE_HTTP_ADDRESS',
    defaultValue: 'localhost:8080'
  },
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_STREAMING_PROXY_ADDRESS',
    defaultValue: 'localhost:50051'
  },
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_INTEGRATION_EXECUTOR_ADDRESS',
    defaultValue: ''
  },
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_MAX_REQUEST_SIZE',
    defaultValue: '30000000' // ~30MB
  },
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_MAX_RESPONSE_SIZE',
    defaultValue: '524288000' // 500MB
  },
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_GRACEFUL_SHUTDOWN_TIMEOUT_MS',
    defaultValue: '600000'
  },
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_WORKER_PLUGINS',
    defaultValue: ''
  },
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_METRICS_PORT',
    defaultValue: '0'
  }
]);

export const SUPERBLOCKS_WORKER_SANDBOX_LOG_LEVEL: string = envs.get('SUPERBLOCKS_WORKER_SANDBOX_LOG_LEVEL');

export const SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_PORT = Number(envs.get('SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_PORT'));

export const SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_VARIABLE_STORE_ADDRESS: string = envs.get(
  'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_VARIABLE_STORE_ADDRESS'
);

export const SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_VARIABLE_STORE_HTTP_ADDRESS: string = envs.get(
  'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_VARIABLE_STORE_HTTP_ADDRESS'
);

export const SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_STREAMING_PROXY_ADDRESS: string = envs.get(
  'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_STREAMING_PROXY_ADDRESS'
);

export const SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_INTEGRATION_EXECUTOR_ADDRESS: string = envs.get(
  'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_INTEGRATION_EXECUTOR_ADDRESS'
);

export const SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_MAX_REQUEST_SIZE = Number(
  envs.get('SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_MAX_REQUEST_SIZE')
);

export const SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_MAX_RESPONSE_SIZE = Number(
  envs.get('SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_MAX_RESPONSE_SIZE')
);

export const SUPERBLOCKS_WORKER_SANDBOX_GRACEFUL_SHUTDOWN_TIMEOUT_MS = Number(
  envs.get('SUPERBLOCKS_WORKER_SANDBOX_GRACEFUL_SHUTDOWN_TIMEOUT_MS')
);

export const SUPERBLOCKS_WORKER_SANDBOX_WORKER_PLUGINS: string = envs.get('SUPERBLOCKS_WORKER_SANDBOX_WORKER_PLUGINS');

export const SUPERBLOCKS_WORKER_SANDBOX_METRICS_PORT = Number(envs.get('SUPERBLOCKS_WORKER_SANDBOX_METRICS_PORT'));

export default envs;
