import { EnvStore } from '@superblocks/shared';
import dotenv from 'dotenv';

dotenv.config();

const envs = new EnvStore(process.env);

envs.addAll([
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_LOG_LEVEL',
    defaultValue: 'info'
  },
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_PORT',
    defaultValue: '50051'
  },
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_VARIABLE_STORE_ADDRESS',
    defaultValue: 'localhost:50050'
  },
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_STREAMING_PROXY_ADDRESS',
    defaultValue: 'localhost:50051'
  },
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_MAX_REQUEST_SIZE',
    defaultValue: '30000000' // ~30MB
  },
  {
    name: 'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_MAX_RESPONSE_SIZE',
    defaultValue: '100000000' // ~100MB
  }
]);

export const SUPERBLOCKS_WORKER_SANDBOX_LOG_LEVEL: string = envs.get('SUPERBLOCKS_WORKER_SANDBOX_LOG_LEVEL');

export const SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_PORT = Number(envs.get('SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_PORT'));

export const SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_VARIABLE_STORE_ADDRESS: string = envs.get(
  'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_VARIABLE_STORE_ADDRESS'
);

export const SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_STREAMING_PROXY_ADDRESS: string = envs.get(
  'SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_STREAMING_PROXY_ADDRESS'
);

export const SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_MAX_REQUEST_SIZE = Number(
  envs.get('SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_MAX_REQUEST_SIZE')
);

export const SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_MAX_RESPONSE_SIZE = Number(
  envs.get('SUPERBLOCKS_WORKER_SANDBOX_TRANSPORT_GRPC_MAX_RESPONSE_SIZE')
);

export default envs;
