{{- if and .Values.server.deploy .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orchestrator-superblocks-key
  annotations:
    external-secrets.io/force-sync: {{ now | date "2006-01-02T15:04:05Z" | quote }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: orchestrator-superblocks-key
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.superblocksKey.data | nindent 4 }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orchestrator-redis
  annotations:
    external-secrets.io/force-sync: {{ now | date "2006-01-02T15:04:05Z" | quote }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: orchestrator-redis
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.redis.data | nindent 4 }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orchestrator-launchdarkly
  annotations:
    external-secrets.io/force-sync: {{ now | date "2006-01-02T15:04:05Z" | quote }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: orchestrator-launchdarkly
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.launchdarkly.data | nindent 4 }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orchestrator-secrets-encryption
  annotations:
    external-secrets.io/force-sync: {{ now | date "2006-01-02T15:04:05Z" | quote }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: orchestrator-secrets-encryption
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.secretsEncryption.data | nindent 4 }}
{{- end }}
