"use strict";
// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file ai/v1/ai.proto (package ai.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.Task_Mock = exports.Task_Explain = exports.Task_Create_Context = exports.Task_Create = exports.Task_Edit_Context = exports.Task_Edit = exports.Task_Transpile = exports.Task_Debug = exports.Task_Optimize = exports.Task = exports.Message = exports.Persona = exports.Syntax = exports.Role = exports.MODEL = exports.LLM = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
const utils_pb_1 = require("../../common/v1/utils_pb");
const language_pb_1 = require("../../common/v1/language_pb");
/**
 * @generated from enum ai.v1.LLM
 */
var LLM;
(function (LLM) {
    /**
     * @generated from enum value: LLM_UNSPECIFIED = 0;
     */
    LLM[LLM["LLM_UNSPECIFIED"] = 0] = "LLM_UNSPECIFIED";
    /**
     * @generated from enum value: LLM_OPENAI = 1;
     */
    LLM[LLM["LLM_OPENAI"] = 1] = "LLM_OPENAI";
    /**
     * @generated from enum value: LLM_ANTHROPIC = 2;
     */
    LLM[LLM["LLM_ANTHROPIC"] = 2] = "LLM_ANTHROPIC";
    /**
     * @generated from enum value: LLM_MOCK = 3;
     */
    LLM[LLM["LLM_MOCK"] = 3] = "LLM_MOCK";
})(LLM || (exports.LLM = LLM = {}));
// Retrieve enum metadata with: proto3.getEnumType(LLM)
protobuf_1.proto3.util.setEnumType(LLM, "ai.v1.LLM", [
    { no: 0, name: "LLM_UNSPECIFIED" },
    { no: 1, name: "LLM_OPENAI" },
    { no: 2, name: "LLM_ANTHROPIC" },
    { no: 3, name: "LLM_MOCK" },
]);
/**
 * @generated from enum ai.v1.MODEL
 */
var MODEL;
(function (MODEL) {
    /**
     * @generated from enum value: MODEL_UNSPECIFIED = 0;
     */
    MODEL[MODEL["MODEL_UNSPECIFIED"] = 0] = "MODEL_UNSPECIFIED";
    /**
     * @generated from enum value: MODEL_ANTHROPIC_CLAUDE_V1 = 1;
     */
    MODEL[MODEL["MODEL_ANTHROPIC_CLAUDE_V1"] = 1] = "MODEL_ANTHROPIC_CLAUDE_V1";
    /**
     * @generated from enum value: MODEL_ANTHROPIC_CLAUDE_V1_0 = 2;
     */
    MODEL[MODEL["MODEL_ANTHROPIC_CLAUDE_V1_0"] = 2] = "MODEL_ANTHROPIC_CLAUDE_V1_0";
    /**
     * @generated from enum value: MODEL_ANTHROPIC_CLAUDE_V1_2 = 3;
     */
    MODEL[MODEL["MODEL_ANTHROPIC_CLAUDE_V1_2"] = 3] = "MODEL_ANTHROPIC_CLAUDE_V1_2";
    /**
     * @generated from enum value: MODEL_ANTHROPIC_CLAUDE_INSTANT_V1 = 4;
     */
    MODEL[MODEL["MODEL_ANTHROPIC_CLAUDE_INSTANT_V1"] = 4] = "MODEL_ANTHROPIC_CLAUDE_INSTANT_V1";
    /**
     * @generated from enum value: MODEL_ANTHROPIC_CLAUDE_INSTANT_V1_0 = 5;
     */
    MODEL[MODEL["MODEL_ANTHROPIC_CLAUDE_INSTANT_V1_0"] = 5] = "MODEL_ANTHROPIC_CLAUDE_INSTANT_V1_0";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT432K0314 = 6;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT432K0314"] = 6] = "MODEL_OPENAI_GPT432K0314";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT432K0613 = 26;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT432K0613"] = 26] = "MODEL_OPENAI_GPT432K0613";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT432K = 7;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT432K"] = 7] = "MODEL_OPENAI_GPT432K";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT40314 = 8;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT40314"] = 8] = "MODEL_OPENAI_GPT40314";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT40613 = 27;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT40613"] = 27] = "MODEL_OPENAI_GPT40613";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT4 = 9;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT4"] = 9] = "MODEL_OPENAI_GPT4";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_5_TURBO_0301 = 10;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_5_TURBO_0301"] = 10] = "MODEL_OPENAI_GPT3_5_TURBO_0301";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_5_TURBO_0613 = 28;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_5_TURBO_0613"] = 28] = "MODEL_OPENAI_GPT3_5_TURBO_0613";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_5_TURBO = 11;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_5_TURBO"] = 11] = "MODEL_OPENAI_GPT3_5_TURBO";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_5_TURBO_16K = 29;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_5_TURBO_16K"] = 29] = "MODEL_OPENAI_GPT3_5_TURBO_16K";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_5_TURBO_16K_0613 = 30;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_5_TURBO_16K_0613"] = 30] = "MODEL_OPENAI_GPT3_5_TURBO_16K_0613";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_TEXT_DAVINCI_003 = 12;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_TEXT_DAVINCI_003"] = 12] = "MODEL_OPENAI_GPT3_TEXT_DAVINCI_003";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_TEXT_DAVINCI_002 = 13;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_TEXT_DAVINCI_002"] = 13] = "MODEL_OPENAI_GPT3_TEXT_DAVINCI_002";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_TEXT_CURIE_001 = 14;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_TEXT_CURIE_001"] = 14] = "MODEL_OPENAI_GPT3_TEXT_CURIE_001";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_TEXT_BAGGAGE_001 = 15;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_TEXT_BAGGAGE_001"] = 15] = "MODEL_OPENAI_GPT3_TEXT_BAGGAGE_001";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_TEXT_ADA_001 = 16;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_TEXT_ADA_001"] = 16] = "MODEL_OPENAI_GPT3_TEXT_ADA_001";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_TEXT_DAVINCI_001 = 17;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_TEXT_DAVINCI_001"] = 17] = "MODEL_OPENAI_GPT3_TEXT_DAVINCI_001";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_DAVINCI_INSTRUCT_BETA = 18;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_DAVINCI_INSTRUCT_BETA"] = 18] = "MODEL_OPENAI_GPT3_DAVINCI_INSTRUCT_BETA";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_DAVINCI = 19;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_DAVINCI"] = 19] = "MODEL_OPENAI_GPT3_DAVINCI";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_CURIE_INSTRUCT_BETA = 20;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_CURIE_INSTRUCT_BETA"] = 20] = "MODEL_OPENAI_GPT3_CURIE_INSTRUCT_BETA";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_CURIE = 21;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_CURIE"] = 21] = "MODEL_OPENAI_GPT3_CURIE";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_ADA = 22;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_ADA"] = 22] = "MODEL_OPENAI_GPT3_ADA";
    /**
     * @generated from enum value: MODEL_OPENAI_GPT3_BAGGAGE = 23;
     */
    MODEL[MODEL["MODEL_OPENAI_GPT3_BAGGAGE"] = 23] = "MODEL_OPENAI_GPT3_BAGGAGE";
    /**
     * @generated from enum value: MODEL_MOCK_TIER_ONE = 24;
     */
    MODEL[MODEL["MODEL_MOCK_TIER_ONE"] = 24] = "MODEL_MOCK_TIER_ONE";
    /**
     * @generated from enum value: MODEL_MOCK_TIER_TWO = 25;
     */
    MODEL[MODEL["MODEL_MOCK_TIER_TWO"] = 25] = "MODEL_MOCK_TIER_TWO";
})(MODEL || (exports.MODEL = MODEL = {}));
// Retrieve enum metadata with: proto3.getEnumType(MODEL)
protobuf_1.proto3.util.setEnumType(MODEL, "ai.v1.MODEL", [
    { no: 0, name: "MODEL_UNSPECIFIED" },
    { no: 1, name: "MODEL_ANTHROPIC_CLAUDE_V1" },
    { no: 2, name: "MODEL_ANTHROPIC_CLAUDE_V1_0" },
    { no: 3, name: "MODEL_ANTHROPIC_CLAUDE_V1_2" },
    { no: 4, name: "MODEL_ANTHROPIC_CLAUDE_INSTANT_V1" },
    { no: 5, name: "MODEL_ANTHROPIC_CLAUDE_INSTANT_V1_0" },
    { no: 6, name: "MODEL_OPENAI_GPT432K0314" },
    { no: 26, name: "MODEL_OPENAI_GPT432K0613" },
    { no: 7, name: "MODEL_OPENAI_GPT432K" },
    { no: 8, name: "MODEL_OPENAI_GPT40314" },
    { no: 27, name: "MODEL_OPENAI_GPT40613" },
    { no: 9, name: "MODEL_OPENAI_GPT4" },
    { no: 10, name: "MODEL_OPENAI_GPT3_5_TURBO_0301" },
    { no: 28, name: "MODEL_OPENAI_GPT3_5_TURBO_0613" },
    { no: 11, name: "MODEL_OPENAI_GPT3_5_TURBO" },
    { no: 29, name: "MODEL_OPENAI_GPT3_5_TURBO_16K" },
    { no: 30, name: "MODEL_OPENAI_GPT3_5_TURBO_16K_0613" },
    { no: 12, name: "MODEL_OPENAI_GPT3_TEXT_DAVINCI_003" },
    { no: 13, name: "MODEL_OPENAI_GPT3_TEXT_DAVINCI_002" },
    { no: 14, name: "MODEL_OPENAI_GPT3_TEXT_CURIE_001" },
    { no: 15, name: "MODEL_OPENAI_GPT3_TEXT_BAGGAGE_001" },
    { no: 16, name: "MODEL_OPENAI_GPT3_TEXT_ADA_001" },
    { no: 17, name: "MODEL_OPENAI_GPT3_TEXT_DAVINCI_001" },
    { no: 18, name: "MODEL_OPENAI_GPT3_DAVINCI_INSTRUCT_BETA" },
    { no: 19, name: "MODEL_OPENAI_GPT3_DAVINCI" },
    { no: 20, name: "MODEL_OPENAI_GPT3_CURIE_INSTRUCT_BETA" },
    { no: 21, name: "MODEL_OPENAI_GPT3_CURIE" },
    { no: 22, name: "MODEL_OPENAI_GPT3_ADA" },
    { no: 23, name: "MODEL_OPENAI_GPT3_BAGGAGE" },
    { no: 24, name: "MODEL_MOCK_TIER_ONE" },
    { no: 25, name: "MODEL_MOCK_TIER_TWO" },
]);
/**
 * @generated from enum ai.v1.Role
 */
var Role;
(function (Role) {
    /**
     * @generated from enum value: ROLE_UNSPECIFIED = 0;
     */
    Role[Role["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    /**
     * @generated from enum value: ROLE_USER = 1;
     */
    Role[Role["USER"] = 1] = "USER";
    /**
     * @generated from enum value: ROLE_ASSISTANT = 2;
     */
    Role[Role["ASSISTANT"] = 2] = "ASSISTANT";
    /**
     * @generated from enum value: ROLE_SYSTEM = 3;
     */
    Role[Role["SYSTEM"] = 3] = "SYSTEM";
})(Role || (exports.Role = Role = {}));
// Retrieve enum metadata with: proto3.getEnumType(Role)
protobuf_1.proto3.util.setEnumType(Role, "ai.v1.Role", [
    { no: 0, name: "ROLE_UNSPECIFIED" },
    { no: 1, name: "ROLE_USER" },
    { no: 2, name: "ROLE_ASSISTANT" },
    { no: 3, name: "ROLE_SYSTEM" },
]);
/**
 * NOTE(frank): I guess these could just be in the Lnaguage enum.
 *
 * @generated from enum ai.v1.Syntax
 */
var Syntax;
(function (Syntax) {
    /**
     * @generated from enum value: SYNTAX_UNSPECIFIED = 0;
     */
    Syntax[Syntax["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    /**
     * @generated from enum value: SYNTAX_JAVASCRIPT = 1;
     */
    Syntax[Syntax["JAVASCRIPT"] = 1] = "JAVASCRIPT";
    /**
     * @generated from enum value: SYNTAX_PYTHON = 2;
     */
    Syntax[Syntax["PYTHON"] = 2] = "PYTHON";
    /**
     * @generated from enum value: SYNTAX_POSTGRESQL = 3;
     */
    Syntax[Syntax["POSTGRESQL"] = 3] = "POSTGRESQL";
    /**
     * @generated from enum value: SYNTAX_MSSQL = 4;
     */
    Syntax[Syntax["MSSQL"] = 4] = "MSSQL";
    /**
     * @generated from enum value: SYNTAX_MYSQL = 5;
     */
    Syntax[Syntax["MYSQL"] = 5] = "MYSQL";
    /**
     * @generated from enum value: SYNTAX_MARIADB = 6;
     */
    Syntax[Syntax["MARIADB"] = 6] = "MARIADB";
    /**
     * @generated from enum value: SYNTAX_SNOWFLAKE = 7;
     */
    Syntax[Syntax["SNOWFLAKE"] = 7] = "SNOWFLAKE";
    /**
     * @generated from enum value: SYNTAX_COCKROACHDB = 8;
     */
    Syntax[Syntax["COCKROACHDB"] = 8] = "COCKROACHDB";
    /**
     * @generated from enum value: SYNTAX_ROCKSET = 9;
     */
    Syntax[Syntax["ROCKSET"] = 9] = "ROCKSET";
    /**
     * @generated from enum value: SYNTAX_REDSHIFT = 10;
     */
    Syntax[Syntax["REDSHIFT"] = 10] = "REDSHIFT";
    /**
     * @generated from enum value: SYNTAX_BIGQUERY = 11;
     */
    Syntax[Syntax["BIGQUERY"] = 11] = "BIGQUERY";
    /**
     * @generated from enum value: SYNTAX_DYNAMODB = 12;
     */
    Syntax[Syntax["DYNAMODB"] = 12] = "DYNAMODB";
    /**
     * @generated from enum value: SYNTAX_MONGODB = 13;
     */
    Syntax[Syntax["MONGODB"] = 13] = "MONGODB";
    /**
     * @generated from enum value: SYNTAX_BINDING = 14;
     */
    Syntax[Syntax["BINDING"] = 14] = "BINDING";
    /**
     * @generated from enum value: SYNTAX_JSON = 15;
     */
    Syntax[Syntax["JSON"] = 15] = "JSON";
    /**
     * @generated from enum value: SYNTAX_HTML = 16;
     */
    Syntax[Syntax["HTML"] = 16] = "HTML";
    /**
     * @generated from enum value: SYNTAX_API = 17;
     */
    Syntax[Syntax["API"] = 17] = "API";
    /**
     * @generated from enum value: SYNTAX_PLUGIN_RESTAPI = 18;
     */
    Syntax[Syntax["PLUGIN_RESTAPI"] = 18] = "PLUGIN_RESTAPI";
    /**
     * @generated from enum value: SYNTAX_PLUGIN_GRAPHQL = 19;
     */
    Syntax[Syntax["PLUGIN_GRAPHQL"] = 19] = "PLUGIN_GRAPHQL";
    /**
     * @generated from enum value: SYNTAX_ORACLEDB = 20;
     */
    Syntax[Syntax["ORACLEDB"] = 20] = "ORACLEDB";
    /**
     * @generated from enum value: SYNTAX_DATABRICKS = 21;
     */
    Syntax[Syntax["DATABRICKS"] = 21] = "DATABRICKS";
})(Syntax || (exports.Syntax = Syntax = {}));
// Retrieve enum metadata with: proto3.getEnumType(Syntax)
protobuf_1.proto3.util.setEnumType(Syntax, "ai.v1.Syntax", [
    { no: 0, name: "SYNTAX_UNSPECIFIED" },
    { no: 1, name: "SYNTAX_JAVASCRIPT" },
    { no: 2, name: "SYNTAX_PYTHON" },
    { no: 3, name: "SYNTAX_POSTGRESQL" },
    { no: 4, name: "SYNTAX_MSSQL" },
    { no: 5, name: "SYNTAX_MYSQL" },
    { no: 6, name: "SYNTAX_MARIADB" },
    { no: 7, name: "SYNTAX_SNOWFLAKE" },
    { no: 8, name: "SYNTAX_COCKROACHDB" },
    { no: 9, name: "SYNTAX_ROCKSET" },
    { no: 10, name: "SYNTAX_REDSHIFT" },
    { no: 11, name: "SYNTAX_BIGQUERY" },
    { no: 12, name: "SYNTAX_DYNAMODB" },
    { no: 13, name: "SYNTAX_MONGODB" },
    { no: 14, name: "SYNTAX_BINDING" },
    { no: 15, name: "SYNTAX_JSON" },
    { no: 16, name: "SYNTAX_HTML" },
    { no: 17, name: "SYNTAX_API" },
    { no: 18, name: "SYNTAX_PLUGIN_RESTAPI" },
    { no: 19, name: "SYNTAX_PLUGIN_GRAPHQL" },
    { no: 20, name: "SYNTAX_ORACLEDB" },
    { no: 21, name: "SYNTAX_DATABRICKS" },
]);
/**
 * @generated from enum ai.v1.Persona
 */
var Persona;
(function (Persona) {
    /**
     * @generated from enum value: PERSONA_UNSPECIFIED = 0;
     */
    Persona[Persona["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    /**
     * @generated from enum value: PERSONA_DEVELOPER = 1;
     */
    Persona[Persona["DEVELOPER"] = 1] = "DEVELOPER";
    /**
     * @generated from enum value: PERSONA_TEACHER = 2;
     */
    Persona[Persona["TEACHER"] = 2] = "TEACHER";
})(Persona || (exports.Persona = Persona = {}));
// Retrieve enum metadata with: proto3.getEnumType(Persona)
protobuf_1.proto3.util.setEnumType(Persona, "ai.v1.Persona", [
    { no: 0, name: "PERSONA_UNSPECIFIED" },
    { no: 1, name: "PERSONA_DEVELOPER" },
    { no: 2, name: "PERSONA_TEACHER" },
]);
/**
 * @generated from message ai.v1.Message
 */
class Message extends protobuf_1.Message {
    /**
     * @generated from field: ai.v1.Role role = 1;
     */
    role = Role.UNSPECIFIED;
    /**
     * @generated from field: string content = 2;
     */
    content = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "ai.v1.Message";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "role", kind: "enum", T: protobuf_1.proto3.getEnumType(Role) },
        { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new Message().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Message().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Message().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Message, a, b);
    }
}
exports.Message = Message;
/**
 * @generated from message ai.v1.Task
 */
class Task extends protobuf_1.Message {
    /**
     * @generated from oneof ai.v1.Task.kind
     */
    kind = { case: undefined };
    /**
     * @generated from field: repeated ai.v1.Message history = 6;
     */
    history = [];
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "ai.v1.Task";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "optimize", kind: "message", T: Task_Optimize, oneof: "kind" },
        { no: 2, name: "edit", kind: "message", T: Task_Edit, oneof: "kind" },
        { no: 3, name: "explain", kind: "message", T: Task_Explain, oneof: "kind" },
        { no: 4, name: "create", kind: "message", T: Task_Create, oneof: "kind" },
        { no: 5, name: "debug", kind: "message", T: Task_Debug, oneof: "kind" },
        { no: 7, name: "transpile", kind: "message", T: Task_Transpile, oneof: "kind" },
        { no: 8, name: "mock", kind: "message", T: Task_Mock, oneof: "kind" },
        { no: 6, name: "history", kind: "message", T: Message, repeated: true },
    ]);
    static fromBinary(bytes, options) {
        return new Task().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Task().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Task().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Task, a, b);
    }
}
exports.Task = Task;
/**
 *
 *
 * @generated from message ai.v1.Task.Optimize
 */
class Task_Optimize extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "ai.v1.Task.Optimize";
    static fields = protobuf_1.proto3.util.newFieldList(() => []);
    static fromBinary(bytes, options) {
        return new Task_Optimize().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Task_Optimize().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Task_Optimize().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Task_Optimize, a, b);
    }
}
exports.Task_Optimize = Task_Optimize;
/**
 *
 *
 * @generated from message ai.v1.Task.Debug
 */
class Task_Debug extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "ai.v1.Task.Debug";
    static fields = protobuf_1.proto3.util.newFieldList(() => []);
    static fromBinary(bytes, options) {
        return new Task_Debug().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Task_Debug().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Task_Debug().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Task_Debug, a, b);
    }
}
exports.Task_Debug = Task_Debug;
/**
 *
 *
 * @generated from message ai.v1.Task.Transpile
 */
class Task_Transpile extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "ai.v1.Task.Transpile";
    static fields = protobuf_1.proto3.util.newFieldList(() => []);
    static fromBinary(bytes, options) {
        return new Task_Transpile().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Task_Transpile().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Task_Transpile().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Task_Transpile, a, b);
    }
}
exports.Task_Transpile = Task_Transpile;
/**
 * @generated from message ai.v1.Task.Edit
 */
class Task_Edit extends protobuf_1.Message {
    /**
     * @generated from field: string prompt = 1;
     */
    prompt = "";
    /**
     * @generated from field: ai.v1.Syntax syntax = 2;
     */
    syntax = Syntax.UNSPECIFIED;
    /**
     * @generated from field: string snippet = 3;
     */
    snippet = "";
    /**
     * @generated from field: ai.v1.Task.Edit.Context context = 4;
     */
    context;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "ai.v1.Task.Edit";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "prompt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "syntax", kind: "enum", T: protobuf_1.proto3.getEnumType(Syntax) },
        { no: 3, name: "snippet", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 4, name: "context", kind: "message", T: Task_Edit_Context },
    ]);
    static fromBinary(bytes, options) {
        return new Task_Edit().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Task_Edit().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Task_Edit().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Task_Edit, a, b);
    }
}
exports.Task_Edit = Task_Edit;
/**
 * @generated from message ai.v1.Task.Edit.Context
 */
class Task_Edit_Context extends protobuf_1.Message {
    /**
     * @generated from oneof ai.v1.Task.Edit.Context.configuration
     */
    configuration = { case: undefined };
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "ai.v1.Task.Edit.Context";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "metadata", kind: "message", T: protobuf_1.Struct, oneof: "configuration" },
        { no: 2, name: "configuration_ids", kind: "message", T: utils_pb_1.StringList, oneof: "configuration" },
    ]);
    static fromBinary(bytes, options) {
        return new Task_Edit_Context().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Task_Edit_Context().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Task_Edit_Context().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Task_Edit_Context, a, b);
    }
}
exports.Task_Edit_Context = Task_Edit_Context;
/**
 * @generated from message ai.v1.Task.Create
 */
class Task_Create extends protobuf_1.Message {
    /**
     * @generated from field: string prompt = 1;
     */
    prompt = "";
    /**
     * @generated from field: ai.v1.Syntax syntax = 2;
     */
    syntax = Syntax.UNSPECIFIED;
    /**
     * @generated from field: ai.v1.Task.Create.Context context = 3;
     */
    context;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "ai.v1.Task.Create";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "prompt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "syntax", kind: "enum", T: protobuf_1.proto3.getEnumType(Syntax) },
        { no: 3, name: "context", kind: "message", T: Task_Create_Context },
    ]);
    static fromBinary(bytes, options) {
        return new Task_Create().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Task_Create().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Task_Create().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Task_Create, a, b);
    }
}
exports.Task_Create = Task_Create;
/**
 * @generated from message ai.v1.Task.Create.Context
 */
class Task_Create_Context extends protobuf_1.Message {
    /**
     * @generated from oneof ai.v1.Task.Create.Context.configuration
     */
    configuration = { case: undefined };
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "ai.v1.Task.Create.Context";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "metadata", kind: "message", T: protobuf_1.Struct, oneof: "configuration" },
        { no: 2, name: "configuration_ids", kind: "message", T: utils_pb_1.StringList, oneof: "configuration" },
    ]);
    static fromBinary(bytes, options) {
        return new Task_Create_Context().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Task_Create_Context().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Task_Create_Context().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Task_Create_Context, a, b);
    }
}
exports.Task_Create_Context = Task_Create_Context;
/**
 * @generated from message ai.v1.Task.Explain
 */
class Task_Explain extends protobuf_1.Message {
    /**
     * @generated from field: ai.v1.Syntax syntax = 1;
     */
    syntax = Syntax.UNSPECIFIED;
    /**
     * @generated from field: string snippet = 2;
     */
    snippet = "";
    /**
     * @generated from field: string contents = 3;
     */
    contents = "";
    /**
     * @generated from field: common.v1.Language language = 4;
     */
    language = language_pb_1.Language.UNSPECIFIED;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "ai.v1.Task.Explain";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "syntax", kind: "enum", T: protobuf_1.proto3.getEnumType(Syntax) },
        { no: 2, name: "snippet", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "contents", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 4, name: "language", kind: "enum", T: protobuf_1.proto3.getEnumType(language_pb_1.Language) },
    ]);
    static fromBinary(bytes, options) {
        return new Task_Explain().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Task_Explain().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Task_Explain().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Task_Explain, a, b);
    }
}
exports.Task_Explain = Task_Explain;
/**
 * @generated from message ai.v1.Task.Mock
 */
class Task_Mock extends protobuf_1.Message {
    /**
     * @generated from field: ai.v1.Syntax syntax = 1;
     */
    syntax = Syntax.UNSPECIFIED;
    /**
     * @generated from field: string shape = 2;
     */
    shape = "";
    /**
     * @generated from field: string prompt = 3;
     */
    prompt = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "ai.v1.Task.Mock";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "syntax", kind: "enum", T: protobuf_1.proto3.getEnumType(Syntax) },
        { no: 2, name: "shape", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "prompt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new Task_Mock().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Task_Mock().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Task_Mock().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Task_Mock, a, b);
    }
}
exports.Task_Mock = Task_Mock;
//# sourceMappingURL=ai_pb.map