---
apiVersion: v2
name: orchestrator
description: A Helm chart for the 'Orchestrator' component of the Superblocks Agent Platform.
type: application
version: 0.0.1
appVersion: "latest"
dependencies:
  - name: valkey
    version: 5.1.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: queue.deploy
  - name: sandbox_workers
    version: 0.0.1
    repository: "file://../../workers/ephemeral/helm"
    condition: sandbox_workers.deploy
