export const SQL_SINGLE_TABLE_METADATA = `SELECT
c.NAME as column_name,
type_name(c.SYSTEM_TYPE_ID) AS data_type,
type_name(c.USER_TYPE_ID) AS user_type,
c.MAX_LENGTH AS max_length,
c.PRECISION AS precision,
c.SCALE AS scale
FROM SYS.TABLES t
JOIN SYS.COLUMNS c ON t.OBJECT_ID = c.OBJECT_ID
JOIN SYS.SCHEMAS s ON t.SCHEMA_ID = s.SCHEMA_ID
WHERE s.name = @PARAM_1
AND t.name = @PARAM_2;`;

export const DEFAULT_SCHEMA_QUERY = `SELECT SCHEMA_NAME() AS current_schema;`;

// rows with default schema will be listed first
export const TABLE_QUERY = `SELECT TABLE_SCHEMA AS table_schema, TABLE_NAME AS table_name, COLUMN_NAME AS column_name, DATA_TYPE AS data_type
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA != 'sys'
ORDER BY CASE WHEN TABLE_SCHEMA = SCHEMA_NAME() THEN 0 ELSE 1 END, TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION;`;

export const KEYS_QUERY = `SELECT TABLE_NAME AS table_name, COLUMN_NAME as column_name
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE OBJECTPROPERTY(OBJECT_ID(CONSTRAINT_SCHEMA + '.' + QUOTENAME(CONSTRAINT_NAME)), 'IsPrimaryKey') = 1;`;

export const PRIMARY_KEY_QUERY = `SELECT TABLE_NAME AS table_name, COLUMN_NAME AS column_name
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE OBJECTPROPERTY(OBJECT_ID(CONSTRAINT_SCHEMA + '.' + QUOTENAME(CONSTRAINT_NAME)), 'IsPrimaryKey') = 1
  AND TABLE_SCHEMA = @PARAM_1
  AND TABLE_NAME = @PARAM_2;`;
