---
packages:
  - 'packages/**'
  - '../ephemeral/javascript-sandbox'
onlyBuiltDependencies:
  - '@swc/core'
  - aws-sdk
  - bcrypt
  - couchbase
  - cpu-features
  - deasync
  - esbuild
  - lz4
  - nice-napi
  - node-expat
  - oracledb
  - protobufjs
  - ssh2
