"use strict";
// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file integration/v1/configuration.proto (package integration.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetConfigurationsResponse = exports.GetConfigurationsRequest = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
const service_pb_1 = require("../../api/v1/service_pb");
const errors_pb_1 = require("../../common/v1/errors_pb");
/**
 * @generated from message integration.v1.GetConfigurationsRequest
 */
class GetConfigurationsRequest extends protobuf_1.Message {
    /**
     * @generated from field: api.v1.Profile profile = 1;
     */
    profile;
    /**
     * @generated from field: repeated string integration_ids = 2;
     */
    integrationIds = [];
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "integration.v1.GetConfigurationsRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "profile", kind: "message", T: service_pb_1.Profile },
        { no: 2, name: "integration_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    ]);
    static fromBinary(bytes, options) {
        return new GetConfigurationsRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GetConfigurationsRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GetConfigurationsRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(GetConfigurationsRequest, a, b);
    }
}
exports.GetConfigurationsRequest = GetConfigurationsRequest;
/**
 * @generated from message integration.v1.GetConfigurationsResponse
 */
class GetConfigurationsResponse extends protobuf_1.Message {
    /**
     * @generated from field: map<string, google.protobuf.Struct> configurations = 1;
     */
    configurations = {};
    /**
     * @generated from field: common.v1.Error error = 2;
     */
    error;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "integration.v1.GetConfigurationsResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "configurations", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "message", T: protobuf_1.Struct } },
        { no: 2, name: "error", kind: "message", T: errors_pb_1.Error },
    ]);
    static fromBinary(bytes, options) {
        return new GetConfigurationsResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GetConfigurationsResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GetConfigurationsResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(GetConfigurationsResponse, a, b);
    }
}
exports.GetConfigurationsResponse = GetConfigurationsResponse;
//# sourceMappingURL=configuration_pb.map