---
apiVersion: v3
name: worker_js
description: A Helm chart for the worker component of the Superblocks Agent Platform.
type: application
version: 0.0.1
appVersion: "latest"
dependencies:
  - name: redis
    version: 22.0.7
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: queue.deploy
