{{- if .Values.image.credentials -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: workers-docker
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: workers-redis-token
data:
  token: {{ .Values.queue.token | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: workers-kvstore-token
data:
  token: {{ .Values.kvstore.token | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: workers-agent-key
data:
  key: {{ .Values.superblocks.key | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: workers-tunnel-private-key-rsa
data:
  key: {{ .Values.superblocks.privateKeyRSA | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: workers-tunnel-private-key-ed25519
data:
  key: {{ .Values.superblocks.privateKeyEd25519 | b64enc }}
