// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	redis "workers/ephemeral/task-manager/internal/store/redis"

	mock "github.com/stretchr/testify/mock"
)

// ExecutionContextProvider is an autogenerated mock type for the ExecutionContextProvider type
type ExecutionContextProvider struct {
	mock.Mock
}

type ExecutionContextProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *ExecutionContextProvider) EXPECT() *ExecutionContextProvider_Expecter {
	return &ExecutionContextProvider_Expecter{mock: &_m.Mock}
}

// CleanupExecution provides a mock function with given fields: executionID
func (_m *ExecutionContextProvider) CleanupExecution(executionID string) {
	_m.Called(executionID)
}

// ExecutionContextProvider_CleanupExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupExecution'
type ExecutionContextProvider_CleanupExecution_Call struct {
	*mock.Call
}

// CleanupExecution is a helper method to define mock.On call
//   - executionID string
func (_e *ExecutionContextProvider_Expecter) CleanupExecution(executionID interface{}) *ExecutionContextProvider_CleanupExecution_Call {
	return &ExecutionContextProvider_CleanupExecution_Call{Call: _e.mock.On("CleanupExecution", executionID)}
}

func (_c *ExecutionContextProvider_CleanupExecution_Call) Run(run func(executionID string)) *ExecutionContextProvider_CleanupExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ExecutionContextProvider_CleanupExecution_Call) Return() *ExecutionContextProvider_CleanupExecution_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutionContextProvider_CleanupExecution_Call) RunAndReturn(run func(string)) *ExecutionContextProvider_CleanupExecution_Call {
	_c.Run(run)
	return _c
}

// GetFileContext provides a mock function with given fields: executionID
func (_m *ExecutionContextProvider) GetFileContext(executionID string) *redis.ExecutionFileContext {
	ret := _m.Called(executionID)

	if len(ret) == 0 {
		panic("no return value specified for GetFileContext")
	}

	var r0 *redis.ExecutionFileContext
	if rf, ok := ret.Get(0).(func(string) *redis.ExecutionFileContext); ok {
		r0 = rf(executionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.ExecutionFileContext)
		}
	}

	return r0
}

// ExecutionContextProvider_GetFileContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileContext'
type ExecutionContextProvider_GetFileContext_Call struct {
	*mock.Call
}

// GetFileContext is a helper method to define mock.On call
//   - executionID string
func (_e *ExecutionContextProvider_Expecter) GetFileContext(executionID interface{}) *ExecutionContextProvider_GetFileContext_Call {
	return &ExecutionContextProvider_GetFileContext_Call{Call: _e.mock.On("GetFileContext", executionID)}
}

func (_c *ExecutionContextProvider_GetFileContext_Call) Run(run func(executionID string)) *ExecutionContextProvider_GetFileContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ExecutionContextProvider_GetFileContext_Call) Return(_a0 *redis.ExecutionFileContext) *ExecutionContextProvider_GetFileContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExecutionContextProvider_GetFileContext_Call) RunAndReturn(run func(string) *redis.ExecutionFileContext) *ExecutionContextProvider_GetFileContext_Call {
	_c.Call.Return(run)
	return _c
}

// SetAllowedKeys provides a mock function with given fields: executionID, keys
func (_m *ExecutionContextProvider) SetAllowedKeys(executionID string, keys []string) {
	_m.Called(executionID, keys)
}

// ExecutionContextProvider_SetAllowedKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAllowedKeys'
type ExecutionContextProvider_SetAllowedKeys_Call struct {
	*mock.Call
}

// SetAllowedKeys is a helper method to define mock.On call
//   - executionID string
//   - keys []string
func (_e *ExecutionContextProvider_Expecter) SetAllowedKeys(executionID interface{}, keys interface{}) *ExecutionContextProvider_SetAllowedKeys_Call {
	return &ExecutionContextProvider_SetAllowedKeys_Call{Call: _e.mock.On("SetAllowedKeys", executionID, keys)}
}

func (_c *ExecutionContextProvider_SetAllowedKeys_Call) Run(run func(executionID string, keys []string)) *ExecutionContextProvider_SetAllowedKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string))
	})
	return _c
}

func (_c *ExecutionContextProvider_SetAllowedKeys_Call) Return() *ExecutionContextProvider_SetAllowedKeys_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutionContextProvider_SetAllowedKeys_Call) RunAndReturn(run func(string, []string)) *ExecutionContextProvider_SetAllowedKeys_Call {
	_c.Run(run)
	return _c
}

// SetFileContext provides a mock function with given fields: executionID, ctx
func (_m *ExecutionContextProvider) SetFileContext(executionID string, ctx *redis.ExecutionFileContext) {
	_m.Called(executionID, ctx)
}

// ExecutionContextProvider_SetFileContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFileContext'
type ExecutionContextProvider_SetFileContext_Call struct {
	*mock.Call
}

// SetFileContext is a helper method to define mock.On call
//   - executionID string
//   - ctx *redis.ExecutionFileContext
func (_e *ExecutionContextProvider_Expecter) SetFileContext(executionID interface{}, ctx interface{}) *ExecutionContextProvider_SetFileContext_Call {
	return &ExecutionContextProvider_SetFileContext_Call{Call: _e.mock.On("SetFileContext", executionID, ctx)}
}

func (_c *ExecutionContextProvider_SetFileContext_Call) Run(run func(executionID string, ctx *redis.ExecutionFileContext)) *ExecutionContextProvider_SetFileContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*redis.ExecutionFileContext))
	})
	return _c
}

func (_c *ExecutionContextProvider_SetFileContext_Call) Return() *ExecutionContextProvider_SetFileContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutionContextProvider_SetFileContext_Call) RunAndReturn(run func(string, *redis.ExecutionFileContext)) *ExecutionContextProvider_SetFileContext_Call {
	_c.Run(run)
	return _c
}

// SetSecurityViolationHandler provides a mock function with given fields: handler
func (_m *ExecutionContextProvider) SetSecurityViolationHandler(handler redis.SecurityViolationHandler) {
	_m.Called(handler)
}

// ExecutionContextProvider_SetSecurityViolationHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSecurityViolationHandler'
type ExecutionContextProvider_SetSecurityViolationHandler_Call struct {
	*mock.Call
}

// SetSecurityViolationHandler is a helper method to define mock.On call
//   - handler redis.SecurityViolationHandler
func (_e *ExecutionContextProvider_Expecter) SetSecurityViolationHandler(handler interface{}) *ExecutionContextProvider_SetSecurityViolationHandler_Call {
	return &ExecutionContextProvider_SetSecurityViolationHandler_Call{Call: _e.mock.On("SetSecurityViolationHandler", handler)}
}

func (_c *ExecutionContextProvider_SetSecurityViolationHandler_Call) Run(run func(handler redis.SecurityViolationHandler)) *ExecutionContextProvider_SetSecurityViolationHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(redis.SecurityViolationHandler))
	})
	return _c
}

func (_c *ExecutionContextProvider_SetSecurityViolationHandler_Call) Return() *ExecutionContextProvider_SetSecurityViolationHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutionContextProvider_SetSecurityViolationHandler_Call) RunAndReturn(run func(redis.SecurityViolationHandler)) *ExecutionContextProvider_SetSecurityViolationHandler_Call {
	_c.Run(run)
	return _c
}

// NewExecutionContextProvider creates a new instance of ExecutionContextProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutionContextProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExecutionContextProvider {
	mock := &ExecutionContextProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
