#!/command/with-contenv sh

export SUPERBLOCKS_WORKER_GO_SUPERBLOCKS_KEY="${SUPERBLOCKS_AGENT_KEY:-${SB_AGENT_KEY:-${SUPERBLOCKS_WORKER_GO_SUPERBLOCKS_KEY}}}"
export SUPERBLOCKS_WORKER_GO_LOG_LEVEL="${SUPERBLOCKS_WORKER_GO_LOG_LEVEL:-${SUPERBLOCKS_AGENT_LOG_LEVEL}}"

echo "{\"level\":\"info\",\"ts\":$(date +%s%3N),\"msg\":\"starting component worker.go\",\"component\":\"s6\"}"
s6-setuidgid 1000:1000 /app/worker.go/bin
