{{- if .Values.queue.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: worker-redis-token
data:
  token: {{ .Values.queue.token | b64enc }}
{{- end }}

{{- if .Values.kvstore.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: worker-kvstore-token
data:
  token: {{ .Values.kvstore.token | b64enc }}
{{- end }}

{{- if .Values.superblocks.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: worker-agent-key
data:
  key: {{ .Values.superblocks.key | b64enc }}
{{- end }}
