name: Bump Versions in Chart.yaml
on:
  release:
    types:
      - published

jobs:
  bump-version:
    name: Bump app version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PACKAGES_READ_TOKEN }}

      - name: Bump app version
        run: |
          pip install pybump
          pybump bump --file helm/v2/Chart.yaml --level minor
          pybump set --file helm/v2/Chart.yaml --app-version --set-version ${{github.event.release.tag_name}}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_PACKAGES_READ_TOKEN }}
          commit-message: "[CI] Bump Chart and App Version"
          committer: Superblocks Admin <admin@superblockshq.com>
          author: Superblocks Admin <admin@superblockshq.com>
          signoff: false
          branch: bump-app-version-${{github.event.release.tag_name}}
          delete-branch: true
          title: '[CI] Bump OPA version in chart to ${{github.event.release.tag_name}}'
          body: |
            Autogenerated PR to bump the App Version in the chart to ${{github.event.release.tag_name}}.
          team-reviewers: |
            engineering
          draft: false
