name: Release Chart
on:
  release:
    types:
      - published

jobs:
  bump-version:
    name: Bump app version
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GH_PACKAGES_READ_TOKEN }}
      - name: Bump app version
        run: |
          pip install pybump
          pybump bump --file helm/Chart.yaml --level minor
          pybump set --file helm/Chart.yaml --app-version --set-version ${{github.event.release.tag_name}}
          git config user.name "superblocksadmin"
          git config user.email "admin@superblockshq.com"
          git add helm/Chart.yaml
          git commit -m "[CI] Bump app version"
          git pull -r && git push
