name: Release Chart V2
on:
  push:
    branches:
      - main
    paths:
      - 'helm/v2/**'

jobs:
  release-chart:
    name: Chart release
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Helm release
        uses: superblocksteam/helm-release-action@v0.3
        with:
          repo: s3://superblocks-public-helm-repo/superblocks
          chart: ./helm/v2
          forceRelease: false
